(() => {
  if(window.__FORTIFY_ACCOUNTABILITY_V2)return;window.__FORTIFY_ACCOUNTABILITY_V2=true;
  const KEY='fortify_mvp_v1',PREF='fortify_plus_prefs_v1',$=s=>document.querySelector(s);
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const prefs=()=>{try{return JSON.parse(localStorage.getItem(PREF)||'{}')}catch{return {}}};
  const savePrefs=p=>localStorage.setItem(PREF,JSON.stringify(p));
  const active=()=>!!window.FORTIFY_PLUS_ACTIVE;
  const today=()=>new Date().toISOString().slice(0,10);
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function style(){if($('#accountabilityV2Styles'))return;const s=document.createElement('style');s.id='accountabilityV2Styles';s.textContent=`
  .acct-v2{margin-top:18px}.acct-person{display:flex;align-items:center;gap:12px;padding:14px;border:1px solid var(--line);border-radius:16px;background:#101214}.acct-avatar{width:46px;height:46px;border-radius:50%;display:grid;place-items:center;background:#211c10;border:1px solid #5a4a28;color:var(--gold2);font-weight:900}.acct-person b,.acct-person small{display:block}.acct-person small{color:var(--muted);margin-top:3px}.acct-status{margin-top:12px;padding:12px;border-radius:14px;background:#101214;border:1px solid var(--line);color:var(--muted)}.acct-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.acct-toggle{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid var(--line);gap:12px}.acct-toggle input{width:auto;margin:0}.acct-preview{white-space:pre-wrap;padding:14px;border-left:3px solid var(--gold);background:#101214;border-radius:10px;margin:14px 0;color:var(--text);line-height:1.45}.acct-log{display:grid;gap:8px;margin-top:10px}.acct-log div{padding:11px 12px;border:1px solid var(--line);border-radius:12px;background:#101214}.acct-log small{display:block;color:var(--muted);margin-top:3px}@media(max-width:420px){.acct-grid{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function buildMessage(){const d=read(),p=prefs(),streak=window.FortifyMetrics?.current?.()||0,checks=(d.checkins||[]).filter(x=>x.date===today()),check=checks[checks.length-1],parts=['Fortify accountability check-in:'];if(p.shareStreak!==false)parts.push(`${streak} day${streak===1?'':'s'} current streak.`);if(p.shareCheckin!==false)parts.push(check?`Today’s check-in: ${check.clean?'clean':'slipped'}.`:'I haven’t completed today’s check-in yet.');if(p.shareUrges){const u=(d.urges||[]).filter(x=>x.date===today()),won=u.filter(x=>x.overcome).length;parts.push(`Urges today: ${won}/${u.length} overcome.`)}parts.push('Please check in with me when you can.');return parts.join(' ')}
  function inject(){style();const card=$('#plusToolsCard');if(!card||$('#accountabilityV2'))return;const marker=card.querySelector('.soft-rule');const wrap=document.createElement('div');wrap.id='accountabilityV2';wrap.className='acct-v2';wrap.innerHTML=`<div class="section-title">Accountability 2.0</div><p class="muted">Send a deliberate check-in without exposing your journal, prayer list, notes, or recovery details.</p><div id="acctPerson"></div><div class="acct-status" id="acctStatus"></div><div class="acct-grid"><button class="gold compact" id="acctShare">Share check-in</button><button class="primary compact" id="acctPreview">Preview message</button></div><div id="acctPreviewBox" hidden></div><div class="acct-toggle"><div><b>Share current streak</b><small class="muted">Only the number of days</small></div><input type="checkbox" id="acctShareStreak"></div><div class="acct-toggle"><div><b>Share today’s check-in</b><small class="muted">Clean / slipped / not completed</small></div><input type="checkbox" id="acctShareCheckin"></div><div class="acct-toggle"><div><b>Share urge count</b><small class="muted">Only today’s total and wins</small></div><input type="checkbox" id="acctShareUrges"></div><p class="muted"><b>Always private:</b> journal entries, prayer list, check-in notes, trigger details, relapse reflection and recovery plan.</p><div class="section-title">Recent accountability</div><div class="acct-log" id="acctLog"></div>`;marker?.parentNode.insertBefore(wrap,marker);render();bind()}
  function render(){const p=prefs(),name=p.accountabilityName||'No partner set',contact=p.accountabilityContact||'Add a phone number or email above';if($('#acctPerson'))$('#acctPerson').innerHTML=`<div class="acct-person"><div class="acct-avatar">${esc((p.accountabilityName||'?').trim().slice(0,1).toUpperCase())}</div><div><b>${esc(name)}</b><small>${esc(contact)}</small></div></div>`;if($('#acctStatus'))$('#acctStatus').textContent=active()?'Fortify+ accountability is ready. You choose exactly what is shared.':'Fortify+ is required for Accountability 2.0.';if($('#acctShareStreak'))$('#acctShareStreak').checked=p.shareStreak!==false;if($('#acctShareCheckin'))$('#acctShareCheckin').checked=p.shareCheckin!==false;if($('#acctShareUrges'))$('#acctShareUrges').checked=!!p.shareUrges;const log=p.accountabilityLog||[];if($('#acctLog'))$('#acctLog').innerHTML=log.length?log.slice(-5).reverse().map(x=>`<div><b>${esc(x.type||'Check-in shared')}</b><small>${new Date(x.ts).toLocaleString()}</small></div>`).join(''):'<div><b>No check-ins shared yet</b><small>Your recent accountability activity will appear here.</small></div>'}
  function log(type){const p=prefs();p.accountabilityLog=p.accountabilityLog||[];p.accountabilityLog.push({type,ts:Date.now()});p.accountabilityLog=p.accountabilityLog.slice(-20);savePrefs(p);render()}
  async function share(){if(!active())return alert('Fortify+ is required for Accountability 2.0.');const p=prefs(),msg=buildMessage(),contact=(p.accountabilityContact||'').trim();try{if(navigator.share){await navigator.share({title:'Fortify check-in',text:msg});log('Check-in shared');return}}catch(e){if(e?.name==='AbortError')return}
    if(contact.includes('@')){location.href=`mailto:${encodeURIComponent(contact)}?subject=${encodeURIComponent('Fortify check-in')}&body=${encodeURIComponent(msg)}`;log('Email check-in opened');return}
    if(contact){location.href=`sms:${encodeURIComponent(contact)}?&body=${encodeURIComponent(msg)}`;log('Text check-in opened');return}
    try{await navigator.clipboard.writeText(msg);alert('Check-in copied.');log('Check-in copied')}catch{prompt('Copy this check-in:',msg)}}
  function bind(){['acctShareStreak','acctShareCheckin','acctShareUrges'].forEach(id=>$('#'+id)?.addEventListener('change',()=>{const p=prefs();p.shareStreak=$('#acctShareStreak').checked;p.shareCheckin=$('#acctShareCheckin').checked;p.shareUrges=$('#acctShareUrges').checked;savePrefs(p)}));$('#acctShare')?.addEventListener('click',share);$('#acctPreview')?.addEventListener('click',()=>{if(!active())return;const box=$('#acctPreviewBox');box.hidden=!box.hidden;box.innerHTML=box.hidden?'':`<div class="acct-preview">${esc(buildMessage())}</div>`});$('#saveAccountability')?.addEventListener('click',()=>setTimeout(render,50))}
  function boot(){inject();const obs=new MutationObserver(()=>inject());obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('fortifypluschange',render);window.addEventListener('storage',render)}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();window.FortifyAccountability={share,preview:buildMessage};
})();