(() => {
 if(window.__FORTIFY_ACHIEVEMENTS)return;window.__FORTIFY_ACHIEVEMENTS=true;
 const KEY='fortify_mvp_v1',SEEN='fortify_achievements_seen_v1',$=s=>document.querySelector(s);
 const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}},seen=()=>{try{return JSON.parse(localStorage.getItem(SEEN)||'[]')}catch{return []}};
 const defs=[
  ['streak1','First Step','Complete your first clean day.','1'],['streak3','Momentum','Reach a 3-day streak.','3'],['streak7','One Week Strong','Reach a 7-day streak.','7'],['streak14','Two Weeks','Reach a 14-day streak.','14'],['streak30','Thirty Days','Reach a 30-day streak.','30'],['streak60','Built Different','Reach a 60-day streak.','60'],['streak90','Ninety Days','Reach a 90-day streak.','90'],
  ['urge1','The First No','Overcome your first logged urge.','✦'],['urge10','Urge Crusher','Overcome 10 logged urges.','10'],['urge25','Battle Tested','Overcome 25 logged urges.','25'],
  ['check7','Showing Up','Complete 7 daily check-ins.','✓'],['check30','Intentional','Complete 30 daily check-ins.','30'],['journal5','Clear Mind','Write 5 journal entries.','✎'],['recovery1','Get Back Up','Complete a relapse recovery plan.','↗']
 ];
 function stats(){const d=read(),streak=window.FortifyMetrics?.current?.()||0,wins=(d.urges||[]).filter(x=>x.overcome).length,checks=new Set((d.checkins||[]).map(x=>x.date)).size,journal=(d.journal||[]).length,recovery=(d.relapses||[]).filter(x=>x.recoveryPlan).length;return{d,streak,wins,checks,journal,recovery}}
 function unlocked(id,s){if(id.startsWith('streak'))return s.streak>=+id.slice(6);if(id==='urge1')return s.wins>=1;if(id==='urge10')return s.wins>=10;if(id==='urge25')return s.wins>=25;if(id==='check7')return s.checks>=7;if(id==='check30')return s.checks>=30;if(id==='journal5')return s.journal>=5;if(id==='recovery1')return s.recovery>=1;return false}
 function style(){if($('#achievementStyles'))return;const e=document.createElement('style');e.id='achievementStyles';e.textContent=`.achievement-card{overflow:hidden}.achievement-head{display:flex;justify-content:space-between;align-items:end;gap:12px}.achievement-count{color:var(--gold2);font-weight:900}.badge-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:15px}.badge{min-height:118px;padding:14px;border:1px solid var(--line);border-radius:16px;background:#101214}.badge.locked{opacity:.38;filter:saturate(.2)}.badge-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:#211c10;border:1px solid #5a4a28;color:var(--gold2);font-weight:900;font-size:18px}.badge b,.badge small{display:block}.badge b{margin-top:10px}.badge small{color:var(--muted);margin-top:4px;line-height:1.35}.achievement-pop{text-align:center;padding:28px}.achievement-pop .badge-icon{width:76px;height:76px;margin:4px auto 18px;border-radius:24px;font-size:28px;box-shadow:0 0 40px #c7a45a33}.achievement-pop h2{margin-bottom:7px}.achievement-pop p{color:var(--muted);line-height:1.5}.celebrate-rays{font-size:24px;letter-spacing:9px;color:var(--gold);animation:achPulse 1.2s ease-in-out infinite}@keyframes achPulse{50%{transform:scale(1.08);opacity:.7}}@media(max-width:380px){.badge-grid{grid-template-columns:1fr}}`;document.head.appendChild(e)}
 function inject(){style();const p=$('#progressView');if(!p||$('#achievementCard'))return;const c=document.createElement('div');c.className='card achievement-card';c.id='achievementCard';c.innerHTML='<div class="achievement-head"><div><div class="eyebrow">ACHIEVEMENTS</div><div class="section-title">Milestones earned</div></div><div class="achievement-count" id="achievementCount"></div></div><div class="badge-grid" id="badgeGrid"></div>';const first=p.querySelector('.metric-grid');first?.insertAdjacentElement('afterend',c)}
 function render(){inject();const s=stats(),got=defs.filter(x=>unlocked(x[0],s));if($('#achievementCount'))$('#achievementCount').textContent=`${got.length}/${defs.length}`;if($('#badgeGrid'))$('#badgeGrid').innerHTML=defs.map(([id,title,desc,icon])=>`<div class="badge ${unlocked(id,s)?'':'locked'}"><div class="badge-icon">${icon}</div><b>${title}</b><small>${unlocked(id,s)?desc:'Locked · '+desc}</small></div>`).join('');checkNew(s)}
 function checkNew(s){const old=seen(),earned=defs.filter(x=>unlocked(x[0],s)&&!old.includes(x[0]));if(!earned.length)return;localStorage.setItem(SEEN,JSON.stringify([...new Set([...old,...earned.map(x=>x[0])])]));celebrate(earned[earned.length-1])}
 function celebrate([id,title,desc,icon]){const dlg=$('#flowDialog'),fc=$('#flowContent');if(!dlg||!fc)return;fc.innerHTML=`<div class="achievement-pop"><div class="celebrate-rays">✦ ✦ ✦</div><div class="badge-icon">${icon}</div><div class="eyebrow">ACHIEVEMENT UNLOCKED</div><h2>${title}</h2><p>${desc}</p><button class="gold" id="achievementDone">Keep going</button></div>`;if(!dlg.open)dlg.showModal();$('#achievementDone').onclick=()=>dlg.close()}
 function bind(){render();window.addEventListener('storage',()=>setTimeout(render,20));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')render()});const obs=new MutationObserver(()=>{const p=$('#progressView');if(p&&!$('#achievementCard'))render()});obs.observe(document.body,{childList:true,subtree:true})}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();window.FortifyAchievements={refresh:render};
})();