const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const KEY='fortify_mvp_v1';
const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
const defaultData={startDate:today(),longest:0,reason:'I want freedom because I want a clear mind, stronger discipline, and a closer relationship with God.',checkins:[],urges:[],journal:[],prayers:[],relapses:[]};
let data=load();
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaultData}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function daysBetween(a,b){return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function currentStreak(){let start=data.startDate||today();const lastRelapse=[...data.relapses].sort((a,b)=>b.date.localeCompare(a.date))[0];if(lastRelapse)start=lastRelapse.date;return Math.max(0,daysBetween(start,today()))}
function last30Clean(){const rel=new Set(data.relapses.filter(x=>daysBetween(x.date,today())<30).map(x=>x.date));return Math.max(0,30-rel.size)}
function render(){const streak=currentStreak();data.longest=Math.max(data.longest||0,streak);localStorage.setItem(KEY,JSON.stringify(data));$('#streakDays').textContent=streak;$('#longestStreak').textContent=data.longest;const clean=last30Clean();$('#successRate').textContent=Math.round(clean/30*100)+'%';$('#pCurrent').textContent=streak;$('#pLongest').textContent=data.longest;$('#pClean').textContent=clean;$('#pUrges').textContent=data.urges.filter(x=>x.overcome).length;const cutoff=new Date();cutoff.setDate(cutoff.getDate()-6);const cstr=cutoff.toISOString().slice(0,10);$('#weekClean').textContent=7-data.relapses.filter(x=>x.date>=cstr).length;$('#weekUrges').textContent=data.urges.filter(x=>x.date>=cstr).length;$('#weekJournal').textContent=data.journal.filter(x=>x.date>=cstr).length;$('#reasonInput').value=data.reason||'';renderTriggers();renderCheckins();renderJournal();renderPrayers();renderFaith()}
function renderTriggers(){const counts={};data.urges.forEach(x=>counts[x.trigger]=(counts[x.trigger]||0)+1);const arr=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);const total=arr.reduce((s,x)=>s+x[1],0)||1;$('#triggerBars').innerHTML=arr.length?arr.map(([k,v])=>`<div class="bar-item"><div class="bar-head"><span>${k}</span><b>${Math.round(v/total*100)}%</b></div><div class="bar-track"><div class="bar-fill" style="width:${v/total*100}%"></div></div></div>`).join(''):'<p class="muted">Log an urge and your trigger patterns will appear here.</p>'}
function renderCheckins(){const list=[...data.checkins].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$('#recentCheckins').innerHTML=list.length?list.map(x=>`<div class="timeline-item"><div><b>${fmt(x.date)}</b><div class="muted">Mood ${x.mood}/5 · temptation ${x.temptation}/10</div></div><div>${x.clean?'✓':'Reset'}</div></div>`).join(''):'<p class="muted">No check-ins yet.</p>'}
function renderJournal(){const list=[...data.journal].sort((a,b)=>b.ts-a.ts);$('#journalEntries').innerHTML=list.length?list.map(x=>`<div class="card"><div class="journal-date">${new Date(x.ts).toLocaleString()}</div><div>${escapeHtml(x.text).replace(/\n/g,'<br>')}</div></div>`).join(''):'<p class="muted">Your saved entries will appear here.</p>'}
function renderPrayers(){$('#prayerList').innerHTML=data.prayers.length?data.prayers.map((p,i)=>`<label class="prayer-item"><input type="checkbox" data-prayer="${i}" ${p.done?'checked':''}><span>${escapeHtml(p.text)}</span></label>`).join(''):'<p class="muted">Nothing added yet.</p>';$$('[data-prayer]').forEach(el=>el.onchange=()=>{data.prayers[+el.dataset.prayer].done=el.checked;save()})}
const faith=[['Temptation','Temptation is not the same thing as surrender. Create distance from the trigger, choose the next right action, and remember that escape often looks ordinary: leave the room, put the phone down, call someone.','1 Corinthians 10:13'],['A clean heart','Change is more than white-knuckling a streak. Ask God to reshape what you want, not only restrain what you do.','Psalm 51:10'],['Discipline','Self-control grows through repeated small choices. You do not need to win the next year tonight. Win the next decision.','Galatians 5:22–23'],['After a slip','Shame can turn one mistake into a spiral. Confess, learn what triggered it, make one concrete change, and begin again.','1 John 1:9']];
function renderFaith(){$('#faithCards').innerHTML=faith.map(x=>`<div class="card"><div class="eyebrow">${x[0].toUpperCase()}</div><h3>${x[0]}</h3><p>${x[1]}</p><div class="ref">${x[2]}</div></div>`).join('')}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function nav(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));scrollTo(0,0)}
$$('.nav-btn').forEach(b=>b.onclick=()=>nav(b.dataset.view));$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#settingsBtn').onclick=()=>nav('profile');
const dlg=$('#flowDialog'),fc=$('#flowContent';
function closeFlow(){dlg.close()}
function show(html){fc.innerHTML=`<div class="flow">${html}</div>`;if(!dlg.open)dlg.showModal();const c=$('#flowClose');if(c)c.onclick=closeFlow}
$('#temptedBtn').onclick=()=>temptStep1();
function temptStep1(){show(`<div class="eyebrow">RIGHT NOW</div><h2>Don’t make a decision yet.</h2><p>Give yourself one minute before doing anything else. An urge rises, peaks, and passes. Your only job right now is to create a little space.</p><div class="countdown" id="cd">60</div><button class="primary" id="skipCd">Continue</button><button class="close-link" id="flowClose">Close</button>`);let n=60;const int=setInterval(()=>{if(!dlg.open){clearInterval(int);return}n--;const el=$('#cd');if(el)el.textContent=n;if(n<=0){clearInterval(int);temptStep2()}},1000);$('#skipCd').onclick=()=>{clearInterval(int);temptStep2()}}
function temptStep2(){const triggers=['Boredom','Stress','Social media','Being alone','Anger','Sexual content','Habit','Can’t sleep','Other'];show(`<div class="eyebrow">NOTICE THE PATTERN</div><h2>What triggered this?</h2><div class="flow-actions">${triggers.map(t=>`<button class="trigger-choice">${t}</button>`).join('')}</div><button class="close-link" id="flowClose">Close</button>`);$$('.trigger-choice').forEach(b=>b.onclick=()=>temptStep3(b.textContent))}
function temptStep3(trigger){show(`<div class="eyebrow">REMEMBER WHY</div><h2>This is bigger than a streak.</h2><div class="reason-quote">${escapeHtml(data.reason)}</div><p>Choose one action that physically changes what you’re doing right now.</p><div class="flow-actions">${['Pray for 2 minutes','Leave the room','Go outside','Do 20 pushups','Read scripture','Text accountability partner','10-minute distraction'].map(a=>`<button class="action-choice">${a}</button>`).join('')}</div><button class="close-link" id="flowClose">Close</button>`);$$('.action-choice').forEach(b=>b.onclick=()=>temptStep4(trigger,b.textContent))}
function temptStep4(trigger,action){show(`<div class="eyebrow">MAKE THE MOVE</div><h2>${action}</h2><p>Do that now. When you’re ready, tell Fortify whether the urge passed.</p><div class="flow-actions"><button class="primary-choice" id="passed">The urge passed</button><button id="still">I’m still struggling</button></div><button class="close-link" id="flowClose">Close</button>`);$('#passed').onclick=()=>{data.urges.push({date:today(),ts:Date.now(),trigger,action,overcome:true});save();show(`<div class="eyebrow">VICTORY</div><h2>You chose discipline.</h2><p>That decision matters. Get back to your day instead of continuing to think about the urge.</p><button class="primary" id="doneFlow">Done</button>`);$('#doneFlow').onclick=closeFlow};$('#still').onclick=()=>{data.urges.push({date:today(),ts:Date.now(),trigger,action,overcome:false});save();show(`<div class="eyebrow">KEEP MOVING</div><h2>Make the environment harder to fail in.</h2><p>Put the phone somewhere inconvenient. Leave the room. Get around another person. Take a walk. Pray out loud. Do not negotiate with the urge.</p><div class="flow-actions"><button class="primary-choice" id="retry">Choose another action</button><button id="relapseBtn">I already slipped</button></div>`);$('#retry').onclick=()=>temptStep3(trigger);$('#relapseBtn').onclick=()=>relapseFlow(trigger)}}
function relapseFlow(trigger='Other'){show(`<div class="eyebrow">RESET, DON’T SPIRAL</div><h2>You slipped. Respond well.</h2><p>One bad decision does not need to become an entire bad day. Your streak resets, but your progress does not disappear.</p><label>What will you change next time?</label><textarea id="lesson" rows="4" placeholder="Example: I’ll leave my phone charging outside the bedroom."></textarea><button class="primary" id="saveRelapse">Reset and continue</button>`);$('#saveRelapse').onclick=()=>{data.relapses.push({date:today(),ts:Date.now(),trigger,lesson:$('#lesson').value.trim()});data.startDate=today();save();closeFlow();toast('Reset saved. Start again now.')}}
$('#checkinBtn').onclick=()=>show(`<div class="eyebrow">DAILY CHECK-IN</div><h2>How did today go?</h2><label>Mood (1 low → 5 great)</label><select id="mood"><option>1</option><option>2</option><option selected>3</option><option>4</option><option>5</option></select><label>Temptation level (1–10)</label><input id="temptLevel" type="range" min="1" max="10" value="4"><label>Porn-free today?</label><select id="clean"><option value="yes">Yes</option><option value="no">No</option></select><textarea id="checkNote" rows="3" placeholder="Short note (optional)"></textarea><button class="primary" id="saveCheck">Save check-in</button><button class="close-link" id="flowClose">Cancel</button>`);
document.addEventListener('click',e=>{if(e.target?.id==='saveCheck'){const clean=$('#clean').value==='yes';data.checkins=data.checkins.filter(x=>x.date!==today());data.checkins.push({date:today(),ts:Date.now(),mood:+$('#mood').value,temptation:+$('#temptLevel').value,clean,note:$('#checkNote').value.trim()});save();if(!clean)relapseFlow('Daily check-in');else{closeFlow();toast('Check-in saved')}}});
$('#saveJournal').onclick=()=>{const t=$('#journalText').value.trim();if(!t)return;data.journal.push({date:today(),ts:Date.now(),text:t});$('#journalText').value='';save();toast('Journal saved')};
$('#prayerForm').onsubmit=e=>{e.preventDefault();const t=$('#prayerInput').value.trim();if(!t)return;data.prayers.push({text:t,done:false});$('#prayerInput').value='';save()};
$('#saveReason').onclick=()=>{data.reason=$('#reasonInput').value.trim()||defaultData.reason;save();toast('Reason saved')};
$('#upgradeBtn').onclick=()=>show(`<div class="eyebrow">FORTIFY+</div><h2>Payments aren’t connected yet.</h2><p>This button is ready to be wired to Stripe. The intended price is $2.99/month with a 7-day trial.</p><button class="primary" id="flowClose">Got it</button>`);
$('#resetBtn').onclick=()=>{if(confirm('Erase all Fortify data stored on this device?')){localStorage.removeItem(KEY);data={...defaultData};save();toast('Data reset')}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
