const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='fortify_mvp_v1';
const today=()=>new Date().toISOString().slice(0,10),fmt=d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
const defaultData={startDate:today(),longest:0,reason:'I want freedom because I want a clear mind, stronger discipline, and a closer relationship with God.',checkins:[],urges:[],journal:[],prayers:[],relapses:[]};
let data=load();
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaultData}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render();window.FortifyCloud?.syncSoon?.()}
function daysBetween(a,b){return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function cutoff(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(days-1));return d.toISOString().slice(0,10)}
function currentStreak(){const t=today(),rel=[...(data.relapses||[])].filter(x=>x.date&&x.date<=t).sort((a,b)=>a.date.localeCompare(b.date));if(rel.length)return Math.max(0,daysBetween(rel[rel.length-1].date,t));return Math.max(1,daysBetween(data.startDate||t,t)+1)}
function longestStreak(){const t=today(),start=data.startDate||t,rel=[...(data.relapses||[])].filter(x=>x.date&&x.date>=start&&x.date<=t).sort((a,b)=>a.date.localeCompare(b.date));if(!rel.length)return Math.max(1,daysBetween(start,t)+1,data.longest||0);let best=Math.max(0,daysBetween(start,rel[0].date));for(let i=1;i<rel.length;i++)best=Math.max(best,daysBetween(rel[i-1].date,rel[i].date)-1);best=Math.max(best,daysBetween(rel[rel.length-1].date,t));return Math.max(best,data.longest||0)}
function recorded(days){const cut=cutoff(days),map=new Map();(data.checkins||[]).filter(x=>x.date>=cut&&x.date<=today()).forEach(x=>map.set(x.date,{clean:!!x.clean}));(data.relapses||[]).filter(x=>x.date>=cut&&x.date<=today()).forEach(x=>map.set(x.date,{clean:false}));const vals=[...map.values()],clean=vals.filter(x=>x.clean).length;return{recorded:vals.length,clean,rate:vals.length?Math.round(clean/vals.length*100):null}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const s=currentStreak(),l=longestStreak(),m30=recorded(30),w=recorded(7);data.longest=l;localStorage.setItem(KEY,JSON.stringify(data));$('#streakDays').textContent=s;$('#longestStreak').textContent=l;$('#successRate').textContent=m30.rate===null?'—':m30.rate+'%';$('#pCurrent').textContent=s;$('#pLongest').textContent=l;$('#pClean').textContent=m30.clean;$('#pUrges').textContent=(data.urges||[]).filter(x=>x.overcome).length;$('#weekClean').textContent=w.clean;const c=cutoff(7);$('#weekUrges').textContent=(data.urges||[]).filter(x=>x.date>=c).length;$('#weekJournal').textContent=(data.journal||[]).filter(x=>x.date>=c).length;const rateLabel=$('.hero .muted.center');if(rateLabel)rateLabel.textContent=m30.recorded?`30-day recorded victory rate · ${m30.recorded} day${m30.recorded===1?'':'s'} logged`:'Complete a check-in to start your 30-day rate';const pc=$('#pClean')?.parentElement?.querySelector('small');if(pc)pc.textContent=m30.recorded?`${m30.recorded} recorded days`:'no days logged yet';$('#reasonInput').value=data.reason||'';renderTriggers();renderCheckins();renderJournal();renderPrayers();renderFaith()}
function renderTriggers(){const counts={};(data.urges||[]).forEach(x=>counts[x.trigger]=(counts[x.trigger]||0)+1);const a=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5),t=a.reduce((s,x)=>s+x[1],0)||1;$('#triggerBars').innerHTML=a.length?a.map(([k,v])=>`<div class="bar-item"><div class="bar-head"><span>${esc(k)}</span><b>${Math.round(v/t*100)}%</b></div><div class="bar-track"><div class="bar-fill" style="width:${v/t*100}%"></div></div></div>`).join(''):'<p class="muted">Log an urge and your trigger patterns will appear here.</p>'}
function renderCheckins(){const a=[...(data.checkins||[])].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$('#recentCheckins').innerHTML=a.length?a.map(x=>`<div class="timeline-item"><div><b>${fmt(x.date)}</b><div class="muted">Mood ${x.mood}/5 · temptation ${x.temptation}/10${x.trigger?' · '+esc(x.trigger):''}</div></div><div>${x.clean?'✓':'Reset'}</div></div>`).join(''):'<p class="muted">No check-ins yet.</p>'}
function renderJournal(){const a=[...(data.journal||[])].sort((a,b)=>b.ts-a.ts);$('#journalEntries').innerHTML=a.length?a.map(x=>`<div class="card"><div class="journal-date">${new Date(x.ts).toLocaleString()}</div><div>${esc(x.text).replace(/\n/g,'<br>')}</div></div>`).join(''):'<p class="muted">Your saved entries will appear here.</p>'}
function renderPrayers(){$('#prayerList').innerHTML=(data.prayers||[]).length?data.prayers.map((p,i)=>`<label class="prayer-item"><input type="checkbox" data-prayer="${i}" ${p.done?'checked':''}><span>${esc(p.text)}</span></label>`).join(''):'<p class="muted">Nothing added yet.</p>';$$('[data-prayer]').forEach(e=>e.onchange=()=>{data.prayers[+e.dataset.prayer].done=e.checked;save()})}
const faith=[['Temptation','Temptation is not the same thing as surrender. Create distance from the trigger and choose the next right action.','1 Corinthians 10:13'],['A clean heart','Ask God to reshape what you want, not only restrain what you do.','Psalm 51:10'],['Discipline','Self-control grows through repeated small choices. Win the next decision.','Galatians 5:22–23'],['After a slip','Confess, learn what triggered it, make one concrete change, and begin again.','1 John 1:9']];
function renderFaith(){$('#faithCards').innerHTML=faith.map(x=>`<div class="card"><div class="eyebrow">${x[0].toUpperCase()}</div><h3>${x[0]}</h3><p>${x[1]}</p><div class="ref">${x[2]}</div></div>`).join('')}
function toast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function nav(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));scrollTo(0,0)}
$$('.nav-btn').forEach(b=>b.onclick=()=>nav(b.dataset.view));$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#settingsBtn').onclick=()=>nav('profile');
const dlg=$('#flowDialog'),fc=$('#flowContent');function closeFlow(){dlg.close()}function show(h){fc.innerHTML=`<div class="flow">${h}</div>`;if(!dlg.open)dlg.showModal();const c=$('#flowClose');if(c)c.onclick=closeFlow}
$('#temptedBtn').onclick=()=>tempt1();
function tempt1(){show(`<div class="eyebrow">RIGHT NOW</div><h2>Don’t make a decision yet.</h2><p>Give yourself one minute. Your only job is to create a little space.</p><div class="countdown" id="cd">60</div><button class="primary" id="skipCd">Continue</button><button class="close-link" id="flowClose">Close</button>`);let n=60,i=setInterval(()=>{if(!dlg.open){clearInterval(i);return}n--;const e=$('#cd');if(e)e.textContent=n;if(n<=0){clearInterval(i);tempt2()}},1000);$('#skipCd').onclick=()=>{clearInterval(i);tempt2()}}
function tempt2(){const a=['Boredom','Stress','Social media','Being alone','Anger','Sexual content','Habit','Can’t sleep','Other'];show(`<div class="eyebrow">NOTICE THE PATTERN</div><h2>What triggered this?</h2><div class="flow-actions">${a.map(t=>`<button class="trigger-choice">${t}</button>`).join('')}</div><button class="close-link" id="flowClose">Close</button>`);$$('.trigger-choice').forEach(b=>b.onclick=()=>tempt3(b.textContent))}
function tempt3(trigger){const a=['Pray for 2 minutes','Leave the room','Go outside','Do 20 pushups','Read scripture','Text accountability partner','10-minute distraction'];show(`<div class="eyebrow">REMEMBER WHY</div><h2>This is bigger than a streak.</h2><div class="reason-quote">${esc(data.reason)}</div><p>Choose one action that physically changes what you’re doing.</p><div class="flow-actions">${a.map(x=>`<button class="action-choice">${x}</button>`).join('')}</div><button class="close-link" id="flowClose">Close</button>`);$$('.action-choice').forEach(b=>b.onclick=()=>tempt4(trigger,b.textContent))}
function tempt4(trigger,action){show(`<div class="eyebrow">MAKE THE MOVE</div><h2>${action}</h2><p>Do that now. Then tell Fortify whether the urge passed.</p><div class="flow-actions"><button class="primary-choice" id="passed">The urge passed</button><button id="still">I’m still struggling</button></div><button class="close-link" id="flowClose">Close</button>`);$('#passed').onclick=()=>{data.urges.push({date:today(),ts:Date.now(),trigger,action,overcome:true});save();show(`<div class="eyebrow">VICTORY</div><h2>You chose discipline.</h2><p>That decision matters. Get back to your day.</p><button class="primary" id="flowClose">Done</button>`)};$('#still').onclick=()=>{data.urges.push({date:today(),ts:Date.now(),trigger,action,overcome:false});save();show(`<div class="eyebrow">KEEP MOVING</div><h2>Make the environment harder to fail in.</h2><p>Put the phone somewhere inconvenient. Leave the room. Get around another person. Pray out loud.</p><div class="flow-actions"><button class="primary-choice" id="retry">Choose another action</button><button id="relapseBtn">I already slipped</button></div>`);$('#retry').onclick=()=>tempt3(trigger);$('#relapseBtn').onclick=()=>window.FortifyRecovery?.begin?.(trigger)}}
function relapse(trigger='Other'){window.FortifyRecovery?.begin?.(trigger)}
// Daily Check-In is owned by core-v2.js. Keeping one implementation avoids duplicate save handlers and competing behavior.
$('#saveJournal').onclick=()=>{const t=$('#journalText').value.trim();if(!t)return;data.journal.push({date:today(),ts:Date.now(),text:t});$('#journalText').value='';save();toast('Journal saved')};
$('#prayerForm').onsubmit=e=>{e.preventDefault();const t=$('#prayerInput').value.trim();if(!t)return;data.prayers.push({text:t,done:false,ts:Date.now()});$('#prayerInput').value='';save()};
$('#saveReason').onclick=()=>{data.reason=$('#reasonInput').value.trim()||defaultData.reason;save();toast('Reason saved')};
$('#resetBtn').onclick=()=>{if(confirm('Erase all Fortify data stored on this device?')){localStorage.removeItem(KEY);data={...defaultData};save();toast('Data reset')}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();