(() => {
  if(window.__FORTIFY_DASHBOARD)return;window.__FORTIFY_DASHBOARD=true;
  const KEY='fortify_mvp_v1',$=s=>document.querySelector(s),today=()=>new Date().toISOString().slice(0,10);
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function style(){if($('#dashboardStyles'))return;const e=document.createElement('style');e.id='dashboardStyles';e.textContent=`.today-card{padding:18px}.today-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.today-head b{font-size:18px}.today-pill{font-size:11px;font-weight:900;border-radius:99px;padding:7px 10px;border:1px solid var(--line);color:var(--muted);white-space:nowrap}.today-pill.done{border-color:#47664b;color:#9ed7a5;background:#101812}.today-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.today-item{padding:13px;border-radius:14px;background:#101214;border:1px solid var(--line)}.today-item span,.today-item b{display:block}.today-item span{font-size:10px;color:var(--muted);letter-spacing:.08em}.today-item b{font-size:14px;margin-top:5px;line-height:1.35}.focus-card{border-color:#4c4128;background:linear-gradient(180deg,#211c10,#15171a)}.focus-card h3{margin:7px 0}.focus-card p{color:var(--muted);line-height:1.5;margin-bottom:0}.focus-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}.focus-actions button{margin:0}.risk-note{margin-top:12px;padding:11px 12px;border-radius:12px;background:#0f1113;border:1px solid var(--line);font-size:12px;color:var(--muted)}@media(max-width:380px){.today-grid,.focus-actions{grid-template-columns:1fr}}`;document.head.appendChild(e)}
  function topTrigger(d){const counts={};(d.urges||[]).forEach(x=>{if(x.trigger)counts[x.trigger]=(counts[x.trigger]||0)+1});(d.relapses||[]).forEach(x=>{if(x.trigger)counts[x.trigger]=(counts[x.trigger]||0)+1});return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Not enough data yet'}
  function recentWin(d){const wins=[...(d.checkins||[])].filter(x=>x.win).sort((a,b)=>(b.ts||0)-(a.ts||0));if(wins[0])return wins[0].win;const urges=[...(d.urges||[])].filter(x=>x.overcome).sort((a,b)=>(b.ts||0)-(a.ts||0));return urges[0]?`You overcame a ${urges[0].trigger||'temptation'} urge.`:'Log a win in your next check-in.'}
  function nextMilestone(s){const marks=[1,3,7,14,30,60,90,180,365],next=marks.find(x=>x>s)||Math.ceil((s+1)/365)*365;return{next,remain:Math.max(0,next-s)}}
  function focus(d,s,checked){const hr=new Date().getHours(),tr=topTrigger(d);if(!checked&&hr>=18)return{title:'Close the day intentionally',body:'Your check-in is still open. Take 30 seconds before the evening gets away from you.',action:'checkin'};if(hr>=21)return{title:'Protect the late hours',body:`Late-night autopilot is where small choices matter. Keep your phone out of easy reach and stay deliberate${tr!=='Not enough data yet'?`—especially around ${tr.toLowerCase()}`:''}.`,action:'reset'};if((d.relapses||[]).some(x=>x.date===today()))return{title:'Start the next decision now',body:'Today included a reset. Your job is not to fix the whole week—just follow the recovery plan you already made.',action:'reset'};if((d.urges||[]).filter(x=>x.date===today()&&!x.overcome).length)return{title:'Stay out of the danger zone',body:'You logged a difficult urge today. Change your environment early instead of waiting until willpower is doing all the work.',action:'reset'};return{title:s>=7?'Protect the momentum':'Build today on purpose',body:s>=7?'You have real momentum now. Keep doing the boring things that made the streak possible.':'Don’t chase a perfect day. Win the next decision, then the one after that.',action:'checkin'}}
  function inject(){style();const home=$('#homeView');if(!home||$('#todayCard'))return;const anchor=$('#milestoneCard')||home.querySelector('.hero');const todayCard=document.createElement('div');todayCard.id='todayCard';todayCard.className='card today-card';anchor.insertAdjacentElement('afterend',todayCard);const focusCard=document.createElement('div');focusCard.id='focusCard';focusCard.className='card focus-card';todayCard.insertAdjacentElement('afterend',focusCard)}
  function render(){inject();const d=read(),s=window.FortifyMetrics?.current?.()||+($('#streakDays')?.textContent||0),checked=(d.checkins||[]).some(x=>x.date===today()),m=nextMilestone(s),trigger=topTrigger(d),win=recentWin(d),f=focus(d,s,checked);if($('#todayCard'))$('#todayCard').innerHTML=`<div class="today-head"><div><div class="eyebrow">TODAY</div><b>${checked?'You checked in. Stay intentional.':'Your day is still in progress.'}</b></div><span class="today-pill ${checked?'done':''}">${checked?'✓ CHECKED IN':'CHECK-IN OPEN'}</span></div><div class="today-grid"><div class="today-item"><span>NEXT MILESTONE</span><b>${m.next} days · ${m.remain} to go</b></div><div class="today-item"><span>TOP PATTERN</span><b>${esc(trigger)}</b></div><div class="today-item"><span>RECENT WIN</span><b>${esc(win)}</b></div><div class="today-item"><span>CURRENT STREAK</span><b>${s} ${s===1?'day':'days'}</b></div></div>`;if($('#focusCard')){$('#focusCard').innerHTML=`<div class="eyebrow">YOUR FOCUS RIGHT NOW</div><h3>${esc(f.title)}</h3><p>${esc(f.body)}</p><div class="focus-actions"><button class="gold" id="focusPrimary">${f.action==='reset'?'Quick Reset':'Daily Check-In'}</button><button class="primary" id="focusWhy">Remember my why</button></div><div class="risk-note">Fortify adapts this card using your time of day and the recovery data you choose to log.</div>`;$('#focusPrimary').onclick=()=>f.action==='reset'?$('#quickReset')?.click():$('#checkinBtn')?.click();$('#focusWhy').onclick=()=>{const dlg=$('#flowDialog'),fc=$('#flowContent');if(!dlg||!fc)return;fc.innerHTML=`<div class="flow"><div class="eyebrow">REMEMBER WHY</div><h2>This is what you are protecting.</h2><div class="reason-quote">${esc(d.reason||'Choose freedom, discipline, and the person you want to become.')}</div><button class="gold" id="whyDone">Back to today</button></div>`;if(!dlg.open)dlg.showModal();$('#whyDone').onclick=()=>dlg.close()}}}
  function bind(){render();window.addEventListener('storage',()=>setTimeout(render,25));window.addEventListener('fortifypluschange',render);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')render()});setInterval(render,60000);const obs=new MutationObserver(()=>{if($('#milestoneCard')&&!$('#todayCard'))render()});obs.observe(document.body,{childList:true,subtree:true})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();window.FortifyDashboard={refresh:render};
})();