(() => {
 const KEY='fortify_mvp_v1', ON='fortify_onboarding_v1';
 const $=s=>document.querySelector(s);
 const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
 const write=d=>localStorage.setItem(KEY,JSON.stringify(d));
 function injectHome(){const h=$('#homeView');if(!h)return;const hero=h.querySelector('.hero');if(hero&&!$('#homeGreeting'))hero.insertAdjacentHTML('beforebegin','<div class="home-greeting" id="homeGreeting"></div>');const panic=$('#temptedBtn');if(panic&&!$('#quickReset'))panic.insertAdjacentHTML('afterend','<button class="quick-reset" id="quickReset"><span>60</span><div><b>Quick Reset</b><small>Breathe, pray, move — one minute</small></div><i>›</i></button>');renderGreeting()}
 function renderGreeting(){const e=$('#homeGreeting');if(!e)return;const hr=new Date().getHours(),part=hr<12?'morning':hr<17?'afternoon':'evening';e.innerHTML=`<span>Good ${part}.</span><b>Win the next decision.</b>`}
 function onboarding(){if(localStorage.getItem(ON))return;const dlg=document.createElement('dialog');dlg.className='onboard-dialog';dlg.innerHTML=`<div class="onboard" id="onboard"><div class="onboard-mark">F</div><div class="eyebrow">WELCOME TO FORTIFY</div><h2>Freedom is built one decision at a time.</h2><p>Set up your foundation. You can change this later.</p><label>Why do you want freedom?</label><textarea id="onReason" rows="4" placeholder="I want freedom because..."></textarea><label>When are you most vulnerable?</label><div class="chip-grid" id="onTriggers">${['Late at night','When alone','Stress','Boredom','Social media','Can’t sleep'].map(x=>`<button type="button" class="setup-chip">${x}</button>`).join('')}</div><button class="gold" id="finishOnboarding">Begin my journey</button><button class="close-link" id="skipOnboarding">Set up later</button></div>`;document.body.appendChild(dlg);dlg.showModal();dlg.querySelectorAll('.setup-chip').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$('#finishOnboarding').onclick=()=>{const d=read(),r=$('#onReason').value.trim(),tr=[...dlg.querySelectorAll('.setup-chip.selected')].map(x=>x.textContent);if(r)d.reason=r;d.setupTriggers=tr;d.startDate=d.startDate||new Date().toISOString().slice(0,10);write(d);localStorage.setItem(ON,'1');dlg.close();location.reload()};$('#skipOnboarding').onclick=()=>{localStorage.setItem(ON,'1');dlg.close()}}
 function quickReset(){const old=$('#flowDialog');if(!old)return;const content=$('#flowContent');let n=60;content.innerHTML=`<div class="flow reset-flow"><div class="eyebrow">QUICK RESET</div><h2>Stay here. Don’t negotiate with the urge.</h2><div class="breath-orb"><span id="resetCount">60</span></div><h3 id="resetCue">Breathe slowly.</h3><p>Put both feet on the floor. Inhale for four. Exhale for six.</p><div class="reason-quote">${(read().reason||'Choose who you want to become.').replace(/[&<>]/g,'')}</div><button class="gold" id="resetAction">I’m moving away from the trigger</button><button class="close-link" id="resetClose">Close</button></div>`;old.showModal();const cue=$('#resetCue'),timer=setInterval(()=>{n--;$('#resetCount').textContent=n;if(n===40)cue.textContent='Ask God for strength for this moment.';if(n===20)cue.textContent='Stand up. Change your environment.';if(n<=0){clearInterval(timer);cue.textContent='You made space. Choose the next right action.'}},1000);$('#resetClose').onclick=()=>{clearInterval(timer);old.close()};$('#resetAction').onclick=()=>{clearInterval(timer);old.close();$('#temptedBtn')?.click()}}
 function bind(){injectHome();$('#quickReset')?.addEventListener('click',quickReset);onboarding();setInterval(renderGreeting,60000)}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();