(() => {
  if (window.__FORTIFY_LAUNCH) return;
  window.__FORTIFY_LAUNCH = true;
  const KEY='fortify_mvp_v1', PREF='fortify_plus_prefs_v1';
  const $=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  function style(){if($('#launchStyles'))return;const e=document.createElement('style');e.id='launchStyles';e.textContent=`.safety-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.legal-links{display:flex;gap:14px;flex-wrap:wrap;margin-top:12px}.legal-link{background:none;border:0;padding:0;color:var(--gold2);text-decoration:underline}.legal-copy h3{margin-top:22px}.legal-copy p,.legal-copy li{color:var(--muted);line-height:1.55}.danger-zone{border-color:#6f3131}.danger-zone .section-title{color:#ffadad}.export-note{font-size:12px;color:var(--muted);margin-top:8px}.delete-confirm{padding:13px;border:1px solid #6f3131;background:#221313;border-radius:13px;margin:14px 0;color:#ffd2d2}.status-line{margin-top:10px;font-size:13px;color:var(--muted)}@media(max-width:420px){.safety-grid{grid-template-columns:1fr}}`;document.head.appendChild(e)}
  function inject(){style();const p=$('#profileView');if(!p||$('#accountSafetyCard'))return;const reset=$('#resetBtn');const html=`<div class="card" id="accountSafetyCard"><div class="eyebrow">ACCOUNT & PRIVACY</div><div class="section-title">Your data</div><p class="muted">Export a copy of your Fortify data or review how Fortify handles sensitive recovery information.</p><div class="safety-grid"><button class="primary compact" id="exportFortifyData">Export my data</button><button class="primary compact" id="privacyBtn">Privacy</button></div><div class="legal-links"><button class="legal-link" id="termsBtn">Terms</button><button class="legal-link" id="supportInfoBtn">Safety & support</button></div><div class="export-note">Exports are downloaded directly to this device as a JSON file. Fortify does not include your password.</div><div id="launchStatus" class="status-line"></div></div><div class="card danger-zone" id="dangerZone"><div class="eyebrow">DANGER ZONE</div><div class="section-title">Delete account</div><p class="muted">Permanently deletes your Fortify account and cloud data. This cannot be undone. If Fortify+ is active, cancel it first so billing is not left active.</p><button class="danger-outline" id="deleteAccountBtn">Delete my account</button></div>`;if(reset)reset.insertAdjacentHTML('beforebegin',html);else p.insertAdjacentHTML('beforeend',html)}
  function status(t,bad=false){const e=$('#launchStatus');if(!e)return;e.textContent=t;e.style.color=bad?'#ff9b9b':''}
  async function exportData(){const b=$('#exportFortifyData');b.disabled=true;status('Preparing export…');try{if(window.FortifyCloud?.session && await window.FortifyCloud.session()){try{await window.FortifyCloud.sync()}catch{}}
    const payload={exportedAt:new Date().toISOString(),format:'Fortify data export v1',data:read(),preferences:(()=>{try{return JSON.parse(localStorage.getItem(PREF)||'{}')}catch{return {}}})()};
    const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fortify-export-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Export created on this device.');
  }catch(e){status(e.message||'Could not create export.',true)}finally{b.disabled=false}}
  function legal(title,body){const dlg=$('#flowDialog'),fc=$('#flowContent');if(!dlg||!fc)return;fc.innerHTML=`<div class="flow legal-copy"><div class="eyebrow">FORTIFY</div><h2>${esc(title)}</h2>${body}<button class="primary" id="legalDone">Done</button></div>`;if(!dlg.open)dlg.showModal();$('#legalDone').onclick=()=>dlg.close()}
  function privacy(){legal('Privacy',`<p><b>Effective September 9, 2026.</b></p><p>Fortify is designed around sensitive recovery data. Core progress can exist locally on your device. When you create an account, Fortify can sync recovery data to its private cloud database so you can restore it across devices.</p><h3>Data Fortify may store</h3><p>Account email, streak/profile information, daily check-ins, urge logs, relapse records, journal entries, prayer entries, subscription status, push-notification device tokens, and settings you choose to save.</p><h3>How it is used</h3><p>To provide recovery features, cloud backup, reminders, subscription access, support, security, and product operation. Fortify does not sell recovery or journal data and does not use advertising trackers to build profiles from that information.</p><h3>Accountability</h3><p>Your journal, private notes, prayer list, relapse reflections, and recovery plans are not automatically shared with an accountability partner. Sharing happens only when you intentionally use a sharing feature.</p><h3>Payments</h3><p>Payments are handled by Stripe. Fortify stores subscription status and identifiers needed to provide Fortify+ but does not store your full card number.</p><h3>Your choices</h3><p>You can export your Fortify data from Profile. You can also request permanent account deletion in the app. Active paid subscriptions must be canceled before account deletion so billing is not left running.</p>`)}
  function terms(){legal('Terms',`<p><b>Effective September 9, 2026.</b></p><p>Fortify is a self-help, habit, faith, and accountability tool. It is not medical care, mental-health treatment, emergency support, or a replacement for a licensed professional or clergy member you choose to consult.</p><p>You are responsible for your account credentials, device security, and decisions made using the app. Do not use Fortify as the only source of help during an emergency or crisis.</p><p>Fortify+ subscriptions renew according to the plan shown at checkout until canceled. Billing and cancellation are handled through Stripe during the current web beta. Features, pricing, and beta availability may change before general release.</p><p>The app may occasionally experience outages, syncing errors, notification delays, or data loss. Export important records if you want an additional personal copy.</p>`)}
  function support(){legal('Safety & support',`<p>Fortify is built to help with habits and intentional behavior change, not emergencies.</p><p>If pornography use or sexual behavior is causing severe distress, interfering with daily life, or feels impossible to control, consider reaching out to a qualified mental-health professional or another trusted support person.</p><p>If you are in immediate danger or may harm yourself or someone else, contact emergency services or a crisis service in your country rather than relying on Fortify.</p>`)}
  async function deleteAccount(){const cloud=window.FortifyCloud;if(!cloud?.client){return legal('Account deletion','<p>Cloud account services are unavailable right now. No data was deleted.</p>')};const sess=await cloud.session?.();if(!sess)return legal('Sign in required','<p>Sign in to the Fortify account you want to permanently delete, then try again.</p>');
    legal('Delete account',`<div class="delete-confirm"><b>This is permanent.</b><br>Your cloud account and synced recovery data will be deleted. Local Fortify data on this device will also be erased after deletion succeeds.</div><p>If you currently have Fortify+, cancel it through Manage Fortify+ first.</p><label>Type DELETE to confirm</label><input id="deleteConfirmText" autocomplete="off" placeholder="DELETE"><button class="danger-outline" id="confirmDeleteAccount">Permanently delete account</button><button class="close-link" id="cancelDeleteAccount">Cancel</button>`);
    $('#cancelDeleteAccount').onclick=()=>$('#flowDialog').close();$('#confirmDeleteAccount').onclick=async()=>{if($('#deleteConfirmText').value.trim()!=='DELETE')return;const btn=$('#confirmDeleteAccount');btn.disabled=true;btn.textContent='Deleting…';try{const {data:{session}}=await cloud.client.auth.getSession();if(!session)throw new Error('Your session expired. Sign in again.');const res=await fetch('https://xbovltvoukrobvjjlemo.supabase.co/functions/v1/delete-account',{method:'POST',headers:{'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json'}});const out=await res.json().catch(()=>({}));if(!res.ok){if(out.code==='subscription_active'){btn.disabled=false;btn.textContent='Permanently delete account';return legal('Cancel Fortify+ first','<p>Your subscription still appears active. Open Profile → Manage Fortify+, cancel the subscription, then return here and delete the account. This prevents billing from continuing after the account is gone.</p>')}throw new Error(out.error||'Account deletion failed.')}try{await cloud.client.auth.signOut()}catch{};['fortify_mvp_v1','fortify_plus_prefs_v1','fortify_onboarding_v1','fortify_achievements_seen_v1'].forEach(k=>localStorage.removeItem(k));legal('Account deleted','<p>Your Fortify cloud account was permanently deleted and this device’s Fortify recovery data was cleared.</p><button class="gold" id="reloadAfterDelete">Start fresh</button>');$('#reloadAfterDelete').onclick=()=>location.reload();}catch(e){btn.disabled=false;btn.textContent='Permanently delete account';alert(e.message||'Could not delete account.')}}}
  function bind(){inject();$('#exportFortifyData')?.addEventListener('click',exportData);$('#privacyBtn')?.addEventListener('click',privacy);$('#termsBtn')?.addEventListener('click',terms);$('#supportInfoBtn')?.addEventListener('click',support);$('#deleteAccountBtn')?.addEventListener('click',()=>deleteAccount().catch(e=>alert(e.message||'Could not start deletion.')))}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();