import {SAVE_KEY,ITEMS,RARITIES,BUILDINGS,NPCS,LORE,clamp,item,freshSave,safeSave,stats,equipment,xpNeeded,buildingCost,rng,appearanceOf} from './data.js?v=070';
import {createWorld,fortressWorld} from './world.js?v=070';
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const num=(v,f=0)=>Number.isFinite(+v)?+v:f;
export class Game {
 constructor(storage=globalThis.localStorage){this.storage=storage;this.listeners={};this.state=this.load();this.mode='wilds';this.paused=true;this.time=0;this.tick=0;this.input={x:0,y:0};this.p={x:1000,y:2990,face:1,moving:false,swing:0,invuln:0,dash:0,ward:0};this.cooldowns={heal:0,burst:0,dodge:0,special:0,ward:0};this.effects=[];this.projectiles=[];this.drops=[];this.enemies=[];this.companion={x:950,y:3000,cooldown:0,heal:0};this.seq=0;this.loadRun();this.offline=this.offlineIncome();this.lastAutoSave=0;this.lastCombat=-20;this.attackTimer=0;this.attackCount=0;this.eventTimer=180;this.newLoot=0;}
 on(name,fn){(this.listeners[name]??=[]).push(fn);return()=>this.listeners[name]=this.listeners[name].filter(v=>v!==fn);}
 emit(name,data){for(const fn of this.listeners[name]||[])fn(data);}
 toast(text,type='info'){this.emit('toast',{text,type});}
 load(){try{const text=this.storage.getItem(SAVE_KEY);if(text)return safeSave(JSON.parse(text));const old=JSON.parse(this.storage.getItem('shatterdeep-v03')||'null');if(old&&old.created){const s=freshSave();Object.assign(s,{created:true,name:old.name||'Wanderer',preset:old.preset||'wanderer',skin:old.skin||1,hair:old.hair||0,level:Math.max(1,num(old.level,1)),depth:Math.max(1,num(old.depth,1)),bestDepth:Math.max(1,num(old.depth,1)),kills:num(old.kills),hp:num(old.hp,120)},appearanceOf(old));s.bank={...s.bank,gold:num(old.gold),ember:num(old.ember),stone:num(old.stone)};s.fort={...old.fort};s.inventory=(old.inv||['rust','coat']).filter(id=>ITEMS[id]).map(id=>item(id,s.depth,'legacy-'+id));s.equipment=Object.fromEntries(Object.entries(old.eq||{}).map(([k,v])=>[k,'legacy-'+v]));this.migrated=true;return safeSave(s);}}catch(e){this.loadError=true;}return freshSave();}
 snapshot(){const s=this.state;if(this.mode==='wilds'){s.run={...this.run,x:this.p.x,y:this.p.y,enemies:this.enemies.map(e=>({...e})),drops:this.drops.map(d=>({...d}))};}s.lastSaved=Date.now();return JSON.parse(JSON.stringify(s));}
 save(){try{const snapshot=this.snapshot();this.storage.setItem(SAVE_KEY,JSON.stringify(snapshot));this.emit('save',snapshot);return true;}catch(e){this.emit('saveError','This browser could not save. Export your save in Settings.');return false;}}
 loadRun(){const s=this.state;this.world=createWorld(s.depth);const prior=s.run&&s.run.depth===s.depth?s.run:null;this.run={depth:s.depth,cleared:[],opened:[],started:[],visited:[],checkpoint:{x:1000,y:2990},...prior};for(const k of ['cleared','opened','started','visited'])if(!Array.isArray(this.run[k]))this.run[k]=[];this.p.x=clamp(num(prior?.x,1000),60,1940);this.p.y=clamp(num(prior?.y,2990),80,3120);this.enemies=Array.isArray(prior?.enemies)?prior.enemies.filter(e=>['wolf','alpha','bandit','archer','wretch','stalker','brute','boss'].includes(e.type)&&e.hp>0&&Number.isFinite(e.x)&&Number.isFinite(e.y)).map(e=>({...e,windup:0,charge:0,cooldown:1})):[];this.drops=Array.isArray(prior?.drops)?prior.drops.filter(d=>Number.isFinite(d.x)&&Number.isFinite(d.y)):[];this.seq=Math.max(0,...this.enemies.map(e=>num(e.id,0)))+1;for(const id of this.run.started)if(!this.run.cleared.includes(id)&&!this.enemies.some(e=>e.room===id))this.run.started=this.run.started.filter(v=>v!==id);this.companion.x=this.p.x-45;this.companion.y=this.p.y+35;this.area=this.world.rooms[0];this.projectiles=[];this.effects=[];}
 offlineIncome(){const s=this.state,hours=clamp((Date.now()-s.lastSaved)/3600000,0,8),workers=Math.min(s.survivors.length,1+(s.fort.quarters||0)*3);if(hours<1/60||!workers)return null;const gain={wood:Math.floor(hours*(s.fort.workshop||0)*5*workers),stone:Math.floor(hours*(s.fort.workshop||0)*3*workers),food:Math.floor(hours*(s.fort.farm||0)*4*workers)};for(const[k,v]of Object.entries(gain))s.bank[k]+=v;s.lastSaved=Date.now();this.save();return Object.values(gain).some(v=>v)?gain:null;}
 total(resource){return(this.state.bag[resource]||0)+(this.state.bank[resource]||0);}
 canSpend(cost){return Object.entries(cost).every(([k,n])=>this.total(k)>=n);}
 spend(cost){if(!this.canSpend(cost))return false;for(const[k,n]of Object.entries(cost)){const fromBank=Math.min(n,this.state.bank[k]||0);this.state.bank[k]-=fromBank;this.state.bag[k]=Math.max(0,(this.state.bag[k]||0)-(n-fromBank));}return true;}
 gain(resource,n){this.state.bag[resource]=(this.state.bag[resource]||0)+n;}
 addItem(def,level=this.state.depth,announce=true){const i=item(def,level);if(this.state.inventory.length>=120){this.gain('gold',8+i.rarity*8);if(announce)this.toast('Pack full · loot converted to gold');return null;}this.state.inventory.push(i);this.newLoot++;if(announce){this.toast(`${RARITIES[i.rarity].toUpperCase()} · ${i.name}`,'loot');this.emit('loot',i);}return i;}
 rollLoot(quality=0){const s=this.state,tierChance=Math.random()+(s.perks.fortune||0)*.012+(s.depth>5?.035:0);let rarity=quality>=2?2:0;if(tierChance>.52)rarity=Math.max(rarity,1);if(tierChance>.85)rarity=Math.max(rarity,2);if(tierChance>.975&&s.depth>=2)rarity=3;if(tierChance>.997&&s.depth>=5)rarity=4;if(quality===3)rarity=Math.max(rarity,3);const pool=Object.keys(ITEMS).filter(k=>ITEMS[k].rarity===rarity);return pool[Math.floor(Math.random()*pool.length)]||'iron';}
 equip(uid){const i=this.state.inventory.find(x=>x.uid===uid);if(!i)return;this.state.equipment[i.slot]=uid;this.state.hp=Math.min(this.state.hp,stats(this.state).maxHp);this.save();this.emit('change');this.toast(`${i.name} equipped`);}
 unequip(slot){const uid=this.state.equipment[slot];if(!uid)return false;this.state.equipment[slot]=null;this.state.hp=Math.min(this.state.hp,stats(this.state).maxHp);this.save();this.emit('change');this.toast(`${slot[0].toUpperCase()+slot.slice(1)} unequipped`);return true;}
 salvage(uid){const s=this.state,i=s.inventory.find(x=>x.uid===uid);if(!i||Object.values(s.equipment).includes(uid))return false;s.inventory=s.inventory.filter(x=>x.uid!==uid);s.bank.gold+=5+i.rarity*7+Math.floor(i.level/3);s.bank.stone+=1+i.rarity;if(i.rarity>=2)s.bank.ember++;this.save();this.emit('change');return true;}
 upgradeItem(uid){const s=this.state,i=s.inventory.find(x=>x.uid===uid),lv=s.fort.smith||0;if(!lv){this.toast('Build a Blacksmith at Emberhold first');return false;}if(!i||i.upgrade>=Math.min(30,lv*2)){this.toast('Upgrade the Blacksmith to temper this item further');return false;}const cost={gold:15*(i.upgrade+1),stone:8*(i.upgrade+1)};if(!this.spend(cost)){this.toast('You need more gold and stone');return false;}i.upgrade++;this.save();this.emit('change');this.toast(`${i.name} tempered to +${i.upgrade}`);return true;}
 build(key){if(!BUILDINGS[key])return false;const cost=buildingCost(this.state,key);if(!this.spend(cost)){this.toast('Gather more resources to build this');return false;}this.state.fort[key]=(this.state.fort[key]||0)+1;this.world=fortressWorld(this.state);this.ensureSafePosition();this.state.hp=stats(this.state).maxHp;this.save();this.emit('change');this.toast(`${BUILDINGS[key].name} · Level ${this.state.fort[key]}`,'success');return true;}
 forge(){if(!this.state.fort.forge){this.toast('Build a Rift Forge first');return;}if(!this.spend({gold:45,stone:20,ember:3})){this.toast('Forging needs 45 gold, 20 stone, and 3 ember');return;}const def=this.rollLoot(Math.random()<.15+this.state.fort.forge*.03?3:2);this.addItem(def);this.save();this.emit('change');}
 perk(key){if(this.state.perkPoints<1||!['might','vitality','focus','fortune'].includes(key))return;this.state.perkPoints--;this.state.perks[key]++;this.save();this.emit('change');}
 addXp(n){const s=this.state;s.xp+=n;while(s.xp>=xpNeeded(s)){s.xp-=xpNeeded(s);s.level++;s.perkPoints++;s.hp=stats(s).maxHp;this.toast(`LEVEL ${s.level} · +1 perk point`,'success');this.fx('ring',this.p.x,this.p.y,{color:'#f8cd79',radius:110,life:1});this.emit('level',s.level);}}
 fx(type,x,y,data={}){this.effects.push({type,x,y,life:.5,maxLife:data.life||.5,...data});if(this.effects.length>150)this.effects.splice(0,30);}
 text(text,x,y,color='#eee6cb'){this.fx('text',x,y,{text,color,life:.85});}
 enterFortress(clanLevel=0){if(this.mode==='wilds')this.snapshot();this.mode=clanLevel?'clan':'fortress';this.world=fortressWorld(this.state,clanLevel);this.area={id:"fortress",name:clanLevel?"Clan Stronghold":"Emberhold"};this.p.x=1000;this.p.y=1570;this.ensureSafePosition();this.p.invuln=2;this.effects=[];this.projectiles=[];this.input={x:0,y:0};if(!clanLevel){for(const k of Object.keys(this.state.bag)){this.state.bank[k]+=this.state.bag[k];this.state.bag[k]=0;}this.state.hp=stats(this.state).maxHp;this.toast('Emberhold · resources banked and health restored');}this.save();this.emit('mode',this.mode);}
 leaveFortress(){this.mode='wilds';this.loadRun();this.input={x:0,y:0};this.p.invuln=2;this.emit('mode',this.mode);this.toast('The Gloam Wilds await');}
 spawn(type,x,y,room,elite=false){const s=this.state,scale=1+Math.pow(s.depth-1,.84)*.2,defs={wolf:[38,92,7,6],alpha:[75,116,10,7],bandit:[66,65,10,8],archer:[45,66,9,9],wretch:[72,77,11,10],stalker:[72,136,12,10],brute:[160,46,19,11],boss:[650,53,20,12]};const b=defs[type];const e={id:++this.seq,type,x,y,homeX:x,homeY:y,room,max:Math.round(b[0]*scale*(elite?1.5:1)),hp:Math.round(b[0]*scale*(elite?1.5:1)),speed:b[1],damage:b[2]*(1+(s.depth-1)*.085),sprite:b[3],elite,face:1,cooldown:1,windup:0,flash:0,phase:0,charge:0,slowed:0};this.enemies.push(e);return e;}
 startRoom(room){if(this.run.started.includes(room.id)||['outpost','shrine'].includes(room.id))return;if(room.id==='grove'&&!this.run.cleared.includes('scar'))return;this.run.started.push(room.id);const d=this.state.depth,types={road:['wolf','wolf'],crossing:['wolf','alpha','wolf'],bandits:['bandit','archer','bandit'],scar:['wretch','wolf','wretch'],cemetery:['wretch','brute','archer'],grove:['boss']}[room.id]||[];if(d>=3&&room.id!=='grove')types.push('stalker');if(d>=6&&room.id==='scar')types.push('brute');types.forEach((type,i)=>{const angle=i/types.length*Math.PI*2;this.spawn(type,room.x+Math.cos(angle)*(type==='boss'?0:85),room.y+Math.sin(angle)*65,room.id,d>=4&&i===0);});if(room.id==='grove'){this.toast('THE HOLLOW STAG','boss');this.emit('boss',true);}this.save();}
 completeRoom(id){if(this.run.cleared.includes(id))return;this.run.cleared.push(id);if(id==='road'){this.drops.push({x:this.p.x+25,y:this.p.y,def:'iron',type:'item'});this.toast('The road is clear · a new weapon awaits','success');}if(id==='crossing'){this.run.checkpoint={x:1040,y:2180};this.state.hp=stats(this.state).maxHp;this.toast('Gloam Crossing · checkpoint reached');}if(id==='bandits'){this.gain('wood',20);this.gain('stone',14);this.toast('Encampment cleared · free the survivor','success');}if(id==='scar'){this.gain('ember',2);this.toast('The Rift weakens · seal the scar');}if(id==='cemetery'){this.run.checkpoint={x:1010,y:1310};this.drops.push({x:this.p.x+28,y:this.p.y,def:'emberboots',type:'item'});this.toast('The cemetery is quiet · Hollow Grove lies north','success');}if(id==='grove'){this.state.bosses++;this.gain('gold',80);this.gain('ember',3);this.drops.push({x:1000,y:550,def:this.rollLoot(2),type:'item'});this.addLore(4,false);this.toast('HOLLOW STAG DEFEATED · the Deep Rift is open','boss');this.emit('boss',false);this.emit('victory',this.state.depth);}this.save();}
 damageEnemy(e,amount,source='melee'){if(e.hp<=0)return;let power=amount;if(stats(this.state).effects.includes('rift')&&this.area&&['scar','grove'].includes(this.area.id))power*=1.3;const crit=Math.random()<.07+(this.state.perks.fortune||0)*.005;power=Math.round(power*(crit?1.65:1));e.hp-=power;e.flash=.12;this.text(crit?power+'!':String(power),e.x,e.y-58,crit?'#ffd273':'#f5ebd7');this.fx('spark',e.x,e.y-20,{color:source==='magic'?'#8af1ff':'#ffd191',life:.25});if(e.hp<=0)this.kill(e);}
 kill(e){e.hp=0;this.enemies=this.enemies.filter(x=>x!==e);this.state.kills++;this.addXp(Math.floor((e.type==='boss'?170:e.elite?32:14)*(1+this.state.depth*.08)));this.fx('death',e.x,e.y,{color:e.type==='wolf'?'#63bcd3':'#ad71e8',radius:e.type==='boss'?120:45,life:.7});if(e.type!=='boss'){this.drops.push({x:e.x,y:e.y,type:'gold',amount:e.elite?12:4+Math.floor(this.state.depth/3)});if(Math.random()<.25+(this.state.perks.fortune||0)*.01)this.drops.push({x:e.x+18,y:e.y+12,type:'item',def:this.rollLoot(e.elite?1:0)});if(Math.random()<.35)this.drops.push({x:e.x-10,y:e.y+10,type:'resource',resource:Math.random()<.5?'wood':'stone',amount:3+Math.floor(this.state.depth/5)});}
 if(stats(this.state).effects.includes('cinder')&&!this.exploding){this.exploding=true;this.fx('ring',e.x,e.y,{color:'#ff8b42',radius:105,life:.4});for(const target of this.enemies.slice())if(distance(target,e)<105)this.damageEnemy(target,stats(this.state).damage*.65,'fire');this.exploding=false;}
 if(e.room&&!this.enemies.some(x=>x.room===e.room)){if(e.room==='event'){this.gain('ember',2);this.addItem(this.rollLoot(2));this.toast('Rift Storm survived · bonus loot recovered','success');this.activeEvent=false;}else this.completeRoom(e.room);}this.save();}
 hurt(n){if(this.p.invuln>0||this.mode!=='wilds')return;const st=stats(this.state),reduction=1/(1+st.armor/70);let damage=Math.max(1,Math.round(n*reduction));if(this.p.ward>0){this.p.ward=Math.max(0,this.p.ward-damage);this.fx('ring',this.p.x,this.p.y,{color:'#68dbeb',radius:45,life:.2});return;}this.state.hp-=damage;this.lastCombat=this.time;this.p.invuln=.24;this.text('-'+damage,this.p.x,this.p.y-55,'#ff8689');this.emit('hurt',damage);if(st.effects.includes('ward')&&!this.cooldowns.ward&&damage>=8){this.p.ward=st.maxHp*.2;this.cooldowns.ward=12;this.toast('Emberguard · ward formed');}if(this.state.hp<=0)this.die();}
 die(){const s=this.state;for(const k of ['gold','wood','stone','ember'])s.bag[k]-=Math.ceil(s.bag[k]*.1);s.hp=stats(s).maxHp;this.p.x=num(this.run.checkpoint?.x,1000);this.p.y=num(this.run.checkpoint?.y,2990);this.p.invuln=3;this.enemies=[];this.projectiles=[];this.run.started=this.run.cleared.slice();this.activeEvent=false;this.emit('death');this.emit('boss',false);this.toast('You fell · 10% of carried resources lost. Your gear is safe.','danger');this.save();}
 ability(name){if(this.paused||this.cooldowns[name]>0)return false;const st=stats(this.state);if(name==='heal'){if(this.state.hp>=st.maxHp){this.toast('Health is already full');return false;}this.state.hp=Math.min(st.maxHp,this.state.hp+st.maxHp*.42);this.cooldowns.heal=16;this.fx('ring',this.p.x,this.p.y,{color:'#7af2b9',radius:90,life:.65});this.text('+'+Math.round(st.maxHp*.42),this.p.x,this.p.y-55,'#8cfdbe');}
 if(name==='burst'){this.cooldowns.burst=8*(st.effects.includes('focus')?.8:1);this.fx('ring',this.p.x,this.p.y,{color:'#bb78ff',radius:155,life:.6});for(const e of this.enemies.slice())if(distance(this.p,e)<155){this.damageEnemy(e,st.damage*2.25*st.ability,'magic');e.slowed=2;}this.emit('burst');}
 if(name==='dodge'){this.cooldowns.dodge=2.8;let x=this.input.x||0,y=this.input.y||0;if(Math.hypot(x,y)<.1){x=this.p.face;y=0;}const len=Math.hypot(x,y);this.p.dx=x/len;this.p.dy=y/len;this.p.dash=.22;this.p.invuln=.48;if(st.effects.includes('trail'))this.effects.push({type:'trail',x:this.p.x,y:this.p.y,life:2.8,maxLife:2.8,tick:0,color:'#ff8139',radius:44});}
 if(name==='special'){this.cooldowns.special=6;this.p.swing=.3;this.fx('slash',this.p.x,this.p.y,{color:'#f6c86b',radius:st.range,face:this.p.face,life:.4});const enemies=this.enemies.filter(e=>distance(e,this.p)<st.range+65);for(const e of enemies)this.damageEnemy(e,st.damage*2.5*st.ability,st.weapon==='staff'?'magic':'melee');if(st.weapon==='bow'||st.weapon==='staff')for(const e of this.enemies.slice().filter(e=>distance(e,this.p)<380).slice(0,4))this.shoot(this.p,e,st.damage*1.5,true);}
 this.emit('ability',name);this.save();return true;}
 shoot(from,target,damage,friendly=false){const dx=target.x-from.x,dy=target.y-from.y,d=Math.hypot(dx,dy)||1;this.projectiles.push({x:from.x,y:from.y-15,vx:dx/d*(friendly?390:175),vy:dy/d*(friendly?390:175),life:3,damage,friendly,color:friendly?'#77e6ff':'#f09087',radius:friendly?4:5});}
 enemyAI(e,dt){const d=distance(e,this.p),dx=this.p.x-e.x,dy=this.p.y-e.y,len=d||1; e.face=dx<0?-1:1;e.flash=Math.max(0,e.flash-dt);e.cooldown=Math.max(0,e.cooldown-dt);e.slowed=Math.max(0,e.slowed-dt);if(e.type==='boss'){this.bossAI(e,dt,d,dx,dy);return;}if(d>560){if(distance(e,{x:e.homeX,y:e.homeY})>4){const a=Math.atan2(e.homeY-e.y,e.homeX-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}return;}
 if(e.windup>0){e.windup-=dt;if(e.windup<=0){if(e.type==='archer'){this.shoot(e,{x:e.tx,y:e.ty},e.damage);}else if(e.type==='brute'){this.fx('ring',e.tx,e.ty,{color:'#c970d5',radius:85,life:.35});if(distance(this.p,{x:e.tx,y:e.ty})<85)this.hurt(e.damage*1.4);}else if(d<68)this.hurt(e.damage);e.cooldown=e.type==='alpha'?.95:1.45;}return;}
 const range=e.type==='archer'?230:e.type==='brute'?85:40;if(d<=range&&!e.cooldown){e.windup=e.type==='brute'?.9:e.type==='archer'?.8:.45;e.windupMax=e.windup;e.tx=this.p.x;e.ty=this.p.y;return;}
 if(d>range*.85){let angle=Math.atan2(dy,dx);if(e.type==='stalker')angle+=Math.sin(this.time*3+e.id)*.65;const speed=e.speed*(e.slowed?.5:1);e.x+=Math.cos(angle)*speed*dt;e.y+=Math.sin(angle)*speed*dt;}else if(e.type==='archer'&&d<100){e.x-=dx/len*e.speed*dt;e.y-=dy/len*e.speed*dt;}
 }
 bossAI(e,dt,d,dx,dy){const phase=e.hp/e.max<.35?2:e.hp/e.max<.68?1:0;if(phase>e.phase){e.phase=phase;this.toast(phase===1?'The grove answers · spectral wretches rise':'THE HOLLOW STAG · RIFT-ENRAGED','boss');for(let i=0;i<2;i++)this.spawn(phase===1?'wretch':'stalker',e.x+(i?100:-100),e.y+80,'grove');this.fx('ring',e.x,e.y,{color:'#bb78ff',radius:260,life:1});}
 if(e.charge>0){e.charge-=dt;e.x=clamp(e.x+e.cx*410*dt,710,1290);e.y=clamp(e.y+e.cy*410*dt,300,800);if(d<58)this.hurt(e.damage*1.4);return;}
 if(e.windup>0){e.windup-=dt;if(e.windup<=0){if(e.attack==='charge'){const len=Math.hypot(e.tx-e.x,e.ty-e.y)||1;e.cx=(e.tx-e.x)/len;e.cy=(e.ty-e.y)/len;e.charge=.7;}else if(e.attack==='wave'){this.fx('shockwave',e.x,e.y,{color:'#c779f8',radius:250,life:1,hit:false});}else if(e.attack==='bolts'){for(let i=0;i<8+e.phase*4;i++){const a=i/(8+e.phase*4)*Math.PI*2;this.projectiles.push({x:e.x,y:e.y-25,vx:Math.cos(a)*135,vy:Math.sin(a)*135,life:3,damage:e.damage*.7,friendly:false,color:'#bd7afd',radius:6});}}else if(d<115){this.hurt(e.damage);this.fx('slash',e.x,e.y,{color:'#c487fd',radius:115,life:.35});}e.cooldown=2.6-e.phase*.45;}return;}
 if(!e.cooldown){e.attack=['charge','wave','bolts','swipe'][(e.turn||0)%4];e.turn=(e.turn||0)+1;e.tx=this.p.x;e.ty=this.p.y;e.windup=e.attack==='charge'?1.1:e.attack==='wave'?1.25:.9;e.windupMax=e.windup;this.emit('bossAttack',e.attack);}else if(d>100){const a=Math.atan2(dy,dx);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}
 }
 addLore(i,announce=true){if(this.state.lore.includes(i))return;this.state.lore.push(i);if(announce)this.emit('lore',LORE[i]);}
 available(node){if(this.run.opened.includes(node.id)&&this.mode==='wilds'&&!['camp','deep'].includes(node.type))return false;if(node.requires&&!this.run.cleared.includes(node.requires))return false;if(node.type==='fox'&&this.state.companions.includes('fox'))return false;if(node.type==='rescue'&&this.state.survivors.includes(node.npc))return false;return true;}
 nearestNode(){return this.world.nodes.filter(n=>this.available(n)&&distance(n,this.p)<85).sort((a,b)=>distance(a,this.p)-distance(b,this.p))[0];}
 interact(node=this.nearestNode()){if(!node||this.paused||!this.available(node)||distance(node,this.p)>100)return;const s=this.state;if(node.requires&&!this.run.cleared.includes(node.requires))return;
 switch(node.type){
 case 'wood':case 'stone':{const n=6+Math.floor(Math.random()*5)+Math.floor(s.depth/3);this.gain(node.type,n);this.run.opened.push(node.id);this.p.swing=.4;this.fx('spark',node.x,node.y-10,{color:node.type==='wood'?'#d7b384':'#a9d4df',life:.5});this.toast(`Gathered ${n} ${node.type}`,'success');break;}
 case 'chest':{this.gain('gold',15+Math.floor(s.depth*2));this.gain('wood',12);this.gain('stone',8);if(node.id==='chest'&&s.depth===1){this.addItem('buckler');this.addItem('bow');}else this.addItem(this.rollLoot(1));this.run.opened.push(node.id);this.toast('Cache recovered · gold, wood, stone, and equipment','loot');break;}
 case 'camp':if(this.time-this.lastCombat<5){this.toast('Clear nearby enemies before resting');return;}s.hp=stats(s).maxHp;if(this.mode==='wilds')this.run.checkpoint={x:node.x+30,y:node.y+40};this.toast('Rested · health restored');break;
 case 'lore':this.addLore(node.lore);this.run.opened.push(node.id);break;
 case 'shrine':s.hp=stats(s).maxHp;this.addItem('staff');this.addLore(1);this.run.opened.push(node.id);this.run.checkpoint={x:node.x+40,y:node.y+80};this.fx('ring',node.x,node.y,{color:'#66e9e3',radius:200,life:1});break;
 case 'fox':s.companions.push('fox');s.companion='fox';this.run.opened.push(node.id);this.toast('Wisp has joined you · companion unlocked','success');break;
 case 'rescue':s.survivors.push(node.npc);if(node.npc==='hunter'){s.companions.push('hunter');}this.run.opened.push(node.id);this.emit('dialog',{title:NPCS[node.npc].name+' · '+NPCS[node.npc].role,text:NPCS[node.npc].text+'\n\nThey will be waiting at Emberhold.'});break;
 case 'rift':this.gain('ember',2);this.run.opened.push(node.id);this.fx('ring',node.x,node.y,{color:'#b990fb',radius:230,life:1});this.toast('Rift sealed · +2 ember','success');break;
 case 'deep':this.descend();return;
 case 'building':this.emit('openBuilding',node.building);return;
 case 'depart':this.leaveFortress();return;
 case 'npc':this.emit('dialog',{title:NPCS[node.npc]?.name||'Survivor',text:NPCS[node.npc]?.text||'The fires are burning again.'});return;
 }
 this.save();this.emit('change');}
 descend(){if(!this.run.cleared.includes('grove'))return;const s=this.state;s.depth++;s.bestDepth=Math.max(s.bestDepth,s.depth);s.run=null;s.hp=stats(s).maxHp;this.loadRun();this.eventTimer=200;this.activeEvent=false;this.toast(`WORLD DEPTH ${s.depth} · descend deeper`,'boss');this.save();this.emit('depth',s.depth);}
 objective(){if(this.mode==='clan')return {title:'A fire worth returning to',text:'Walk together. Build a legacy.',target:{x:1000,y:1450}};if(this.mode==='fortress'){const unbuilt=!this.state.fort.smith?'smith':!this.state.fort.quarters?'quarters':'workshop';const n=this.world.nodes.find(n=>n.building===unbuilt);return{title:'Rebuild Emberhold',text:!this.state.fort.smith?'Build the Blacksmith to temper your gear.':'Gather resources. Shelter survivors. Keep the fire lit.',target:n};}const r=this.run;if(!r.opened.includes('chest'))return{title:'The last watch',text:'Search the chest in the ruined outpost.',target:this.world.nodes.find(n=>n.id==='chest')};if(!r.cleared.includes('road'))return{title:'Follow the King’s Road',text:'Head north. Defeat the Gloom Wolves.',target:this.world.rooms[1]};if(!r.cleared.includes('crossing'))return{title:'Find Gloam Crossing',text:'Break through the corrupted wolf pack.',target:this.world.rooms[2]};if(!r.cleared.includes('scar'))return{title:'A wound in the world',text:'Reach the Rift Scar to the north. Explore the side paths.',target:this.world.rooms[5]};if(!r.cleared.includes('cemetery'))return{title:'Beyond the veil',text:'Survive the Forgotten Cemetery.',target:this.world.rooms[6]};if(!r.cleared.includes('grove'))return{title:'Warden of the Gloam',text:'Enter Hollow Grove. Defeat the Hollow Stag.',target:this.world.rooms[7]};return{title:'The descent begins',text:'Collect your reward. Enter the Deep Rift.',target:this.world.nodes.find(n=>n.id==='deep')};}
 isBlocked(x,y,padding=12){return x<65||x>this.world.w-65||y<90||y>this.world.h-70||this.world.props.some(o=>o.solid&&Math.hypot(o.x-x,o.y-y)<o.solid+padding);}
 ensureSafePosition(){if(!this.isBlocked(this.p.x,this.p.y,18))return false;const start={x:this.p.x,y:this.p.y};for(let r=16;r<2200;r+=16)for(let i=0;i<32;i++){const a=i*Math.PI/16,x=start.x+Math.cos(a)*r,y=start.y+Math.sin(a)*r;if(!this.isBlocked(x,y,20)){this.p.x=x;this.p.y=y;this.input={x:0,y:0};this.emit('relocated');return true;}}return false;}
 move(dx,dy,dt,st){if(this.isBlocked(this.p.x,this.p.y))this.ensureSafePosition();let speed=this.p.dash>0?660:st.speed;const nx=clamp(this.p.x+dx*speed*dt,65,this.world.w-65),ny=clamp(this.p.y+dy*speed*dt,90,this.world.h-70);const collides=(x,y)=>this.world.props.some(o=>o.solid&&Math.hypot(o.x-x,o.y-y)<o.solid+12);if(!collides(nx,this.p.y))this.p.x=nx;if(!collides(this.p.x,ny))this.p.y=ny;if(this.mode==='wilds'&&this.p.y<865&&!this.run.cleared.includes('scar')){this.p.y=865;if(this.time-(this.gateToast||-10)>6){this.toast('The Rift Scar must be cleared before entering the grove');this.gateToast=this.time;}}}
 update(dt){if(this.paused)return;dt=clamp(dt,0,.04);this.time+=dt;const st=stats(this.state);for(const k of Object.keys(this.cooldowns))this.cooldowns[k]=Math.max(0,this.cooldowns[k]-dt);this.p.invuln=Math.max(0,this.p.invuln-dt);this.p.swing=Math.max(0,this.p.swing-dt);this.p.dash=Math.max(0,this.p.dash-dt);let dx=this.input.x,dy=this.input.y,len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len;}if(this.p.dash>0){dx=this.p.dx;dy=this.p.dy;}this.p.moving=Math.hypot(dx,dy)>.1;if(this.p.moving){if(Math.abs(dx)>.04)this.p.face=dx<0?-1:1;this.move(dx,dy,dt,st);if(this.p.dash>0)this.fx('afterimage',this.p.x,this.p.y,{life:.18});}
 const oldArea=this.area?.id;this.area=this.world.rooms.find(a=>distance(a,this.p)<a.r)||{id:'wilds',name:this.world.realm.name};if(oldArea!==this.area.id){this.emit('area',this.area);if(this.mode==='wilds'&&!this.run.visited.includes(this.area.id))this.run.visited.push(this.area.id);}
 if(this.mode==='wilds'){
 for(const a of this.world.rooms)if(distance(a,this.p)<a.r+20)this.startRoom(a);
 for(const e of this.enemies.slice())this.enemyAI(e,dt);
 // Resolve crowd overlap without pushing enemies through the player.
 for(let i=0;i<this.enemies.length;i++)for(let j=i+1;j<this.enemies.length;j++){const a=this.enemies[i],b=this.enemies[j],d=distance(a,b);if(d>0&&d<29){const m=(29-d)*.5,ax=(a.x-b.x)/d,ay=(a.y-b.y)/d;a.x+=ax*m;b.x-=ax*m;a.y+=ay*m;b.y-=ay*m;}}
 this.attackTimer-=dt;let target=this.enemies.filter(e=>distance(e,this.p)<st.range).sort((a,b)=>distance(a,this.p)-distance(b,this.p))[0];if(target){this.lastCombat=this.time;if(this.attackTimer<=0){this.attackTimer=st.attackRate;this.p.face=target.x<this.p.x?-1:1;this.p.swing=.24;this.attackCount++;if(st.weapon==='bow'||st.weapon==='staff')this.shoot(this.p,target,st.damage,true);else{this.damageEnemy(target,st.damage);this.fx('slash',this.p.x,this.p.y,{color:'#ebd3a0',radius:st.range,face:this.p.face,life:.2});if(st.weapon==='greatsword')for(const e of this.enemies.slice())if(e!==target&&distance(e,this.p)<st.range)this.damageEnemy(e,st.damage*.55);}if(st.effects.includes('blades')&&this.attackCount%4===0){for(const e of this.enemies.slice().filter(e=>distance(e,this.p)<210).slice(0,3))this.shoot(this.p,e,st.damage*1.2,true);}this.emit('attack');}}
 for(const p of this.projectiles.slice()){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.friendly){const e=this.enemies.find(e=>Math.hypot(e.x-p.x,e.y-20-p.y)<(e.type==='boss'?50:24));if(e){this.damageEnemy(e,p.damage,'magic');p.life=0;}}else if(Math.hypot(this.p.x-p.x,this.p.y-20-p.y)<19){this.hurt(p.damage);p.life=0;}}
 for(const d of this.drops.slice())if(distance(this.p,d)<37){if(d.type==='item')this.addItem(d.def);else this.gain(d.resource||'gold',d.amount||4);this.drops=this.drops.filter(x=>x!==d);this.save();}
 if(this.state.companion){let c=this.companion,d=distance(c,this.p);if(d>55){const a=Math.atan2(this.p.y+25-c.y,this.p.x-30-c.x);c.x+=Math.cos(a)*Math.min(230,d*2)*dt;c.y+=Math.sin(a)*Math.min(230,d*2)*dt;}c.cooldown-=dt;c.heal-=dt;let t=this.enemies.find(e=>distance(e,c)<180);if(t&&c.cooldown<=0){this.shoot(c,t,st.damage*.38*(1+(this.state.fort.barracks||0)*.15),true);c.cooldown=1.8;}if(c.heal<=0&&this.state.fort.pens){this.state.hp=Math.min(st.maxHp,this.state.hp+st.maxHp*.02);c.heal=10;}}
 this.eventTimer-=dt;if(this.eventTimer<=0&&!this.activeEvent&&this.area.id!=='grove'){this.activeEvent=true;this.eventTimer=300;for(let i=0;i<3;i++)this.spawn(i===2?'stalker':'wretch',clamp(this.p.x+(i-1)*100,70,1930),this.p.y-170,'event');this.toast('RIFT STORM · survive the incursion','boss');}
 if(this.time-this.lastCombat>7)this.state.hp=Math.min(st.maxHp,this.state.hp+st.maxHp*.003*dt);
 }
 for(const f of this.effects){f.life-=dt;if(f.type==='shockwave'&&!f.hit){const radius=f.radius*(1-f.life/f.maxLife),d=distance(f,this.p);if(Math.abs(d-radius)<18){this.hurt(22+this.state.depth*2);f.hit=true;}}if(f.type==='trail'){f.tick-=dt;if(f.tick<=0){f.tick=.45;for(const e of this.enemies.slice())if(distance(f,e)<50)this.damageEnemy(e,st.damage*.35,'fire');}}}
 this.effects=this.effects.filter(f=>f.life>0);this.projectiles=this.projectiles.filter(p=>p.life>0);if(this.time-this.lastAutoSave>8){this.lastAutoSave=this.time;this.save();}this.tick++;this.emit('tick');
 }
}
