import {safeSave,SAVE_KEY,appearanceOf} from './data.js?v=070';
const URL='https://xbovltvoukrobvjjlemo.supabase.co';
const KEY='sb_publishable_fHwXDiMLK2bj5gZVU_4Kfg_43VonsAr';
export class Online{
 constructor(game){this.game=game;this.client=null;this.user=null;this.clan=null;this.members=[];this.channel=null;this.connected=false;this.remote=new Map();this.lastBroadcast=0;this.syncing=false;this.saving=false;this.ready=this.init();game.on('mode',()=>{if(this.channel)this.track();});}
 async init(){try{await new Promise((res,rej)=>{if(window.supabase)return res();let s=document.createElement('script');s.src='./assets/supabase-2.57.4.js';s.onload=res;s.onerror=()=>rej(new Error('Online features could not load. Solo play is still available.'));document.head.append(s);});this.client=window.supabase.createClient(URL,KEY,{auth:{storageKey:'shatterdeep-auth-v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false},realtime:{params:{eventsPerSecond:8}}});const {data,error}=await this.client.auth.getSession();if(error)throw error;this.user=data.session?.user||null;this.client.auth.onAuthStateChange((event,session)=>{this.user=session?.user||null;if(event==='TOKEN_REFRESHED')this.client.realtime.setAuth(session.access_token);});if(this.user)await this.refreshClan();return true;}catch(e){this.error=e.message;return false;}}
 assert(){if(!this.client)throw new Error(this.error||'Online services are still loading. Try again in a moment.');if(!navigator.onLine)throw new Error('You are offline. Your solo journey is saved on this device.');}
 async auth(email,password,signup=false){await this.ready;this.assert();if(password.length<8)throw new Error('Use a password with at least 8 characters.');const {data,error}=signup?await this.client.auth.signUp({email,password}):await this.client.auth.signInWithPassword({email,password});if(error)throw error;if(signup&&!data.session)return {confirm:true};this.user=data.user;await this.profile();await this.refreshClan();return {confirm:false};}
 async signout(){if(this.channel)await this.client.removeChannel(this.channel);this.channel=null;await this.client.auth.signOut();this.user=null;this.clan=null;this.members=[];this.connected=false;this.game.peers=[];if(this.game.mode==='clan')this.game.enterFortress();}
 appearance(){const s=this.game.state;return {...appearanceOf(s),preset:s.preset,skin:s.skin,hair:s.hair,body:s.body,equipment:s.equipment,inventory:s.inventory.filter(i=>Object.values(s.equipment).includes(i.uid)),fort:{},perks:{},level:s.level,name:s.name};}
 async profile(){if(!this.user)return;const s=this.game.state;const {error}=await this.client.from('sd_profiles').upsert({id:this.user.id,name:s.name,appearance:this.appearance(),depth:s.bestDepth,level:s.level,updated_at:new Date().toISOString()});if(error)throw error;}
 async saveCloud(){this.assert();if(!this.user)throw new Error('Sign in to save this journey online.');if(this.saving)return;this.saving=true;try{const snapshot=this.game.snapshot();const {error}=await this.client.from('sd_saves').upsert({user_id:this.user.id,data:snapshot,updated_at:new Date().toISOString()});if(error)throw error;await this.profile();this.game.toast('Cloud save updated','success');}finally{this.saving=false;}}
 async getCloud(){this.assert();if(!this.user)throw new Error('Sign in first.');const {data,error}=await this.client.from('sd_saves').select('data,updated_at').eq('user_id',this.user.id).maybeSingle();if(error)throw error;return data;}
 restoreCloud(data){const g=this.game;g.storage.setItem(SAVE_KEY+'-before-cloud',JSON.stringify(g.snapshot()));g.state=safeSave(data);g.mode='wilds';g.loadRun();g.save();g.emit('change');g.emit('mode','wilds');g.toast('Cloud journey restored','success');}
 async createClan(name){this.assert();await this.profile();const {error}=await this.client.rpc('sd_create_clan',{clan_name:name});if(error)throw error;await this.refreshClan();}
 async joinClan(code){this.assert();await this.profile();const {error}=await this.client.rpc('sd_join_clan',{code});if(error)throw error;await this.refreshClan();}
 async leaveClan(){const {error}=await this.client.rpc('sd_leave_clan');if(error)throw error;if(this.channel)await this.client.removeChannel(this.channel);this.channel=null;this.clan=null;this.members=[];this.game.peers=[];if(this.game.mode==='clan')this.game.enterFortress();}
 async refreshClan(){if(!this.user)return;const {data:membership,error:e}=await this.client.from('sd_members').select('*').eq('user_id',this.user.id).maybeSingle();if(e)throw e;if(!membership){this.clan=null;return;}const [c,m]=await Promise.all([this.client.from('sd_clans').select('*').eq('id',membership.clan_id).single(),this.client.from('sd_members').select('*').eq('clan_id',membership.clan_id)]);if(c.error)throw c.error;if(m.error)throw m.error;this.clan=c.data;this.members=m.data;const {data:profiles,error}=await this.client.from('sd_profiles').select('*').in('id',m.data.map(m=>m.user_id));if(error)throw error;this.members=this.members.map(m=>({...m,profile:profiles.find(p=>p.id===m.user_id)}));await this.connect();this.game.emit('online');}
 get clanLevel(){return this.clan?Math.min(16,1+Math.floor(Math.sqrt(this.clan.resources/60))):0;}
 async donate(amount){if(this.donating||this.saving)throw new Error('Wait for the current save or contribution to finish.');this.donating=true;try{this.assert();amount=Math.floor(amount);if(!Number.isFinite(amount)||amount<1||amount>10000)throw new Error('Choose an amount from 1 to 10000.');if(this.game.state.bank.stone<amount)throw new Error('Return to Emberhold to bank enough stone.');await this.saveCloud();const {data,error}=await this.client.rpc('sd_donate',{amount});if(error)throw error;this.game.state.bank.stone-=amount;this.clan.resources=data;this.game.save();await this.refreshClan();if(this.game.mode==='clan')this.game.enterFortress(this.clanLevel);this.game.toast(`Contributed ${amount} stone to ${this.clan.name}`,'success');}finally{this.donating=false;}}
 async connect(){if(!this.clan||this.channel)return;const {data}=await this.client.auth.getSession();this.client.realtime.setAuth(data.session?.access_token);this.channel=this.client.channel('sd-clan-'+this.clan.id,{config:{private:true,broadcast:{self:false},presence:{key:this.user.id}}});this.channel.on('presence',{event:'sync'},()=>{const state=this.channel.presenceState();this.onlineIds=new Set(Object.keys(state));this.updatePeers();}).on('broadcast',{event:'move'},({payload:p})=>{if(!p||typeof p.id!=='string'||!this.members.some(m=>m.user_id===p.id))return;if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>2000||p.y<0||p.y>2400)return;this.remote.set(p.id,{...this.remote.get(p.id),...p,last:performance.now()});this.updatePeers();}).on('broadcast',{event:'emote'},({payload:p})=>{const remote=this.remote.get(p?.id);if(remote&&['👋','⚔️','🔥','❤️'].includes(p.emote)){remote.emote=p.emote;remote.emoteAt=this.game.rendererTime||0;this.updatePeers();}}).subscribe(async status=>{this.connected=status==='SUBSCRIBED';if(this.connected)await this.track();this.game.emit('online');});}
 async track(){if(!this.channel||!this.connected)return;await this.channel.track({id:this.user.id,name:this.game.state.name,place:this.game.mode});}
 updatePeers(){if(!this.clan)return;this.game.peers=this.members.filter(m=>m.user_id!==this.user.id).map((m,i)=>{const r=this.remote.get(m.user_id),live=this.onlineIds?.has(m.user_id)&&r&&r.mode==='clan'&&performance.now()-r.last<7000;return {id:m.user_id,name:m.profile?.name||'Wanderer',x:live?r.x:820+(i%4)*115,y:live?r.y:1430+Math.floor(i/4)*80,face:live?r.face:1,moving:live?r.moving:false,offline:!live,state:m.profile?.appearance?{...m.profile.appearance,inventory:m.profile.appearance.inventory||[],equipment:m.profile.appearance.equipment||{}}:this.game.state,emote:r?.emote,emoteAt:r?.emoteAt};});}
 broadcast(time){if(!this.channel||!this.connected||this.game.mode!=='clan'||time-this.lastBroadcast<.2)return;this.lastBroadcast=time;this.channel.send({type:'broadcast',event:'move',payload:{id:this.user.id,x:this.game.p.x,y:this.game.p.y,face:this.game.p.face,moving:this.game.p.moving,mode:this.game.mode}}).catch(()=>{});}
 async emote(emote){if(!this.connected)throw new Error('The clan connection is not ready.');await this.channel.send({type:'broadcast',event:'emote',payload:{id:this.user.id,emote}});this.game.toast(emote);}
}
