import {PRESETS,COLORS,RARITIES,SKINS,HAIRS,equipment,stats,realmFor,GEAR_ART} from './data.js?v=060';
export class Renderer{
 constructor(game,canvas){this.game=game;this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.images={};this.frames={};this.camera={x:0,y:0};this.avatarCache=new Map();this.ready=false;this.shake=0;this.time=0;this.size={w:100,h:100,z:1};game.on('hurt',()=>{if(game.state.settings.shake)this.shake=5;});game.on('burst',()=>{if(game.state.settings.shake)this.shake=7;});game.on('change',()=>this.avatarCache.clear());game.on('depth',()=>this.snap());game.on('mode',()=>this.snap());}
 async load(){await Promise.all(['actors','props','ground','gear','road'].map(key=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{this.images[key]=im;resolve();};im.onerror=()=>reject(new Error('Could not load '+key+' artwork'));im.src='./assets/'+key+'.webp';})));for(const key of ['actors','props','gear']){this.frames[key]=[];for(let i=0;i<24;i++){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.drawImage(this.images[key],i%6*256,Math.floor(i/6)*256,256,256,0,0,256,256);this.frames[key].push(c);}}this.prepareGear();this.ready=true;this.snap();}
 resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.dpr=dpr;let z=r.width<600?r.width/465:Math.min(1.1,r.height/740+.12);this.size={w:r.width/z,h:r.height/z,z};this.snap();}
 snap(){this.camera.x=this.game.p.x-this.size.w/2;this.camera.y=this.game.p.y-this.size.h*.53;}
 sprite(g,set,index,x,y,size=90,flip=false,alpha=1,angle=0){const c=this.frames[set]?.[index];if(!c)return;g.save();g.globalAlpha=alpha;g.translate(Math.round(x),Math.round(y));if(flip)g.scale(-1,1);if(angle)g.rotate(angle);g.drawImage(c,-size/2,-size*.9,size,size);g.restore();}
 prepareGear(){const boxes=[[82,6,116,249],[24,53,210,197],[8,48,226,202],[10,50,218,200],[1,49,225,207],[2,46,226,209],[10,20,244,230],[24,40,214,211],[45,27,164,228],[26,18,181,232],[0,74,230,153],[18,57,218,179],[22,29,232,197],[25,26,228,201],[38,32,204,177],[25,16,215,197],[19,15,231,198],[34,18,212,197],[15,0,225,244],[12,0,244,230],[12,0,239,243],[18,0,201,204],[28,0,179,233],[20,0,222,245]];this.gearParts=boxes.map((b,i)=>{const c=document.createElement('canvas');c.width=b[2];c.height=b[3];c.getContext('2d').drawImage(this.frames.gear[i],...b,0,0,b[2],b[3]);return c;});}
 gearIcon(g,index,w,h){const a=this.gearParts[index];if(!a)return;const scale=Math.min((w-8)/a.width,(h-8)/a.height);g.imageSmoothingEnabled=false;g.drawImage(a,(w-a.width*scale)/2,(h-a.height*scale)/2,a.width*scale,a.height*scale);}
 avatar(s){const eq=equipment(s),key=[s.preset,s.skin,s.hair,s.body,...Object.values(eq).map(i=>i?.def)].join(',');if(this.avatarCache.has(key))return this.avatarCache.get(key);const c=document.createElement('canvas');c.width=180;c.height=220;const g=c.getContext('2d');g.imageSmoothingEnabled=false;if(s.body){g.translate(90,0);g.scale(1.08,1);g.translate(-90,0);}
 const part=(i,x,y,w,h)=>{if(this.gearParts[i])g.drawImage(this.gearParts[i],x,y,w,h);};
 if(eq.cloak)part(GEAR_ART[eq.cloak.def],38,48,108,160);
 part(0,43,15,94,191);
 // Skin/hair palette belongs only to the uncovered body, never to equipment.
 if(!eq.helmet){g.save();g.globalCompositeOperation='source-atop';g.globalAlpha=.23;g.fillStyle=HAIRS[s.hair||0];g.fillRect(79,15,38,14);g.fillStyle=SKINS[s.skin||0];g.fillRect(86,30,27,19);g.restore();}
 if(eq.chest)part(GEAR_ART[eq.chest.def]??1,39,51,106,88);
 const pair=(i,left,right,w,h)=>{const a=this.gearParts[i];if(!a)return;const half=a.width/2;g.drawImage(a,0,0,half,a.height,...left,w,h);g.drawImage(a,half,0,half,a.height,...right,w,h);};
 if(eq.boots)pair(GEAR_ART[eq.boots.def]??14,[56,165],[101,156],30,43);
 if(eq.gloves)pair(GEAR_ART[eq.gloves.def]??10,[39,108],[126,106],24,37);
 if(eq.helmet)part(GEAR_ART[eq.helmet.def]??8,eq.helmet.def==='hood'?73:81,eq.helmet.def==='hood'?15:15,eq.helmet.def==='hood'?62:44,eq.helmet.def==='hood'?57:45);
 if(eq.shield)part(GEAR_ART[eq.shield.def]??21,23,95,47,61);
 this.avatarCache.set(key,c);return c;}
 animatedBody(g,a,p,time,size){const scale=size*.9/180,walk=p.moving?Math.sin(time*11):0,breath=Math.sin(time*2)*.6,attack=p.swing>0?Math.sin(p.swing/.4*Math.PI):0;g.save();g.translate(-size*.46,-size*.9);g.scale(scale,size*1.1/220);
 const piece=(sx,sy,w,h,px,py,angle=0,dy=0)=>{g.save();g.translate(px,py+dy);g.rotate(angle);g.drawImage(a,sx,sy,w,h,sx-px,sy-py,w,h);g.restore();};
 // Split at hips and shoulders so feet alternate and hands counter-swing.
 piece(0,140,91,80,73,141,walk*.13,Math.max(0,walk)*-6);
 piece(91,140,89,80,111,141,-walk*.13,Math.max(0,-walk)*-6);
 piece(0,0,180,87,90,90,walk*.012,breath-Math.abs(walk)*1.5);
 piece(63,87,59,53,90,90,walk*.012,breath-Math.abs(walk)*1.5);
 piece(0,87,63,53,58,87,-walk*.12-attack*.25,breath);
 piece(122,87,58,53,126,87,walk*.12+attack*.35,breath);
 g.restore();}
 player(g,p,s,size=94,time=0){const eq=equipment(s),a=this.avatar(s),bob=p.moving?Math.sin(time*14)*2:Math.sin(time*2)*.6;this.shadow(g,p.x,p.y,36);g.save();g.translate(p.x,p.y+bob);if(p.face<0)g.scale(-1,1);const rarity=eq.chest?.rarity||eq.weapon?.rarity||0;if(rarity>=3){g.shadowColor=COLORS[RARITIES[rarity]];g.shadowBlur=10;}if(p.invuln>0&&Math.floor(time*18)%2===0)g.globalAlpha=.55;this.animatedBody(g,a,p,time,size);g.shadowBlur=0;const w=eq.weapon;if(w){g.save();g.translate(size*.24,-size*.38);g.rotate(p.swing>0?-1.3+p.swing*7:.6);this.sprite(g,'actors',w.sprite,0,20,(w.kind==='greatsword'?67:w.kind==='staff'?68:55)*size/94,false,1);g.restore();}g.restore();if(p.ward>0){g.strokeStyle='#75dff8';g.lineWidth=1.5;g.beginPath();g.ellipse(p.x,p.y-33,34,45,0,0,Math.PI*2);g.stroke();}}
 shadow(g,x,y,r=30){g.save();g.globalAlpha=.27;g.fillStyle='#000';g.beginPath();g.ellipse(x,y+2,r,r*.29,0,0,Math.PI*2);g.fill();g.restore();}
 light(g,x,y,r,color,alpha=.25){g.save();g.globalAlpha=alpha;g.globalCompositeOperation='screen';const grad=g.createRadialGradient(x,y,0,x,y,r);grad.addColorStop(0,color);grad.addColorStop(.35,color+'66');grad.addColorStop(1,color+'00');g.fillStyle=grad;g.fillRect(x-r,y-r,r*2,r*2);g.restore();}
 roadLayer(world){if(this.roadWorld===world&&this.roadCanvas)return this.roadCanvas;const c=document.createElement('canvas');c.width=world.w/2;c.height=world.h/2;const g=c.getContext('2d');g.scale(.5,.5);g.lineCap='round';g.lineJoin='round';const tile=document.createElement('canvas');tile.width=tile.height=360;tile.getContext('2d').drawImage(this.images.road,0,0,360,360);const pattern=g.createPattern(tile,'repeat');for(const path of world.paths){g.beginPath();path.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));for(const [width,alpha] of [[132,.08],[116,.13],[101,.22],[88,.45],[74,.96]]){g.lineWidth=width;g.globalAlpha=alpha;g.strokeStyle=pattern;g.stroke();}}g.globalAlpha=1;this.roadWorld=world;this.roadCanvas=c;return c;}
 drawRoads(g,world){g.drawImage(this.roadLayer(world),0,0,world.w,world.h);}
 ground(g){const {camera:c,size:s,game}=this;g.fillStyle='#152420';g.fillRect(c.x,c.y,s.w,s.h);const tile=512,startX=Math.floor(c.x/tile)*tile,startY=Math.floor(c.y/tile)*tile;for(let x=startX;x<c.x+s.w;x+=tile)for(let y=startY;y<c.y+s.h;y+=tile)g.drawImage(this.images.ground,x,y,tile,tile);g.fillStyle='#060f13';g.globalAlpha=.35;g.fillRect(c.x,c.y,s.w,s.h);g.globalAlpha=1;
 this.drawRoads(g,game.world);
 if(game.mode==='wilds'){for(const a of game.world.rooms){if(a.id==='grove'){g.strokeStyle='#86788a55';g.lineWidth=5;g.beginPath();g.ellipse(a.x,a.y,256,218,0,0,Math.PI*2);g.stroke();}if(a.id==='scar'){g.save();g.translate(a.x,a.y);g.strokeStyle='#b268dd66';g.lineWidth=3;for(let i=0;i<8;i++){g.rotate(Math.PI/4);g.beginPath();g.moveTo(20,0);g.lineTo(72,-24);g.lineTo(91,13);g.lineTo(172,-8);g.stroke();}g.restore();}}}
 }
 enemy(g,e){this.shadow(g,e.x,e.y,e.type==='boss'?75:e.type==='wolf'||e.type==='alpha'?35:27);g.save();if(e.elite||e.type==='boss'){g.shadowColor=e.type==='boss'?'#48ccf3':'#aa55ee';g.shadowBlur=e.type==='boss'?16:8;}if(e.flash>0)g.filter='brightness(2)';let size=e.type==='boss'?205:e.type==='brute'?112:e.type==='wolf'||e.type==='alpha'?95:88;const stride=e.windup>0?0:Math.sin(this.time*(e.type==='boss'?5:10)+e.id);this.sprite(g,'actors',e.sprite,e.x,e.y+stride*2,size,e.face<0,1,e.windup>0?Math.sin(this.time*22)*.018:stride*.022);g.restore();if(e.type!=='boss'&&(e.hp<e.max||e.elite)){const w=e.elite?54:40;g.fillStyle='#0c1720';g.fillRect(e.x-w/2,e.y-size*.9-9,w,4);g.fillStyle=e.elite?'#c591f6':'#b96467';g.fillRect(e.x-w/2,e.y-size*.9-9,w*e.hp/e.max,4);}if(e.elite){g.fillStyle='#dfb7ff';g.font='11px sans-serif';g.textAlign='center';g.fillText('ELITE',e.x,e.y-size*.9-16);}}
 telegraph(g,e){if(e.windup<=0)return;const p=1-e.windup/e.windupMax;g.save();g.strokeStyle='#ff958c';g.fillStyle='#e4596035';g.lineWidth=2;if(e.type==='boss'&&e.attack==='charge'){let a=Math.atan2(e.ty-e.y,e.tx-e.x);g.translate(e.x,e.y);g.rotate(a);g.fillRect(0,-28,340,56);g.strokeRect(0,-28,340,56);g.fillStyle='#ffc2b4';g.globalAlpha=.2+p*.3;g.fillRect(0,-28,340*p,56);}else if(e.type==='boss'&&e.attack==='wave'){g.beginPath();g.arc(e.x,e.y,250,0,Math.PI*2);g.fill();g.stroke();g.beginPath();g.arc(e.x,e.y,250*p,0,Math.PI*2);g.stroke();}else if(e.type==='archer'){g.setLineDash([7,7]);g.beginPath();g.moveTo(e.x,e.y-20);g.lineTo(e.tx,e.ty-20);g.stroke();}else{const radius=e.type==='brute'?85:e.type==='boss'?115:55;const x=e.type==='brute'?e.tx:e.x,y=e.type==='brute'?e.ty:e.y;g.beginPath();g.ellipse(x,y,radius,radius*.7,0,0,Math.PI*2);g.fill();g.stroke();g.strokeStyle='#ffc0ba';g.beginPath();g.ellipse(x,y,radius,radius*.7,0,-Math.PI/2,-Math.PI/2+Math.PI*2*p);g.stroke();}g.restore();}
 drawEffect(g,f){const p=1-f.life/f.maxLife;g.save();g.globalAlpha=Math.min(1,f.life*3);g.strokeStyle=f.color||'#7edce9';g.fillStyle=f.color||'#7edce9';if(f.type==='text'){g.font='600 17px system-ui';g.textAlign='center';g.shadowColor='#050b0f';g.shadowBlur=4;g.fillText(f.text,f.x,f.y-p*35);}else if(f.type==='ring'||f.type==='shockwave'){g.lineWidth=(1-p)*5+1;g.beginPath();g.ellipse(f.x,f.y,(f.radius||100)*p,(f.radius||100)*p*.7,0,0,Math.PI*2);g.stroke();this.light(g,f.x,f.y,(f.radius||100)*p+20,f.color,.12*(1-p));}else if(f.type==='slash'){g.translate(f.x,f.y-20);if(f.face<0)g.scale(-1,1);g.lineWidth=(1-p)*10+1;g.beginPath();g.arc(0,0,f.radius*.72,-1.6+p,1.4+p);g.stroke();}else if(f.type==='trail'){g.globalAlpha=.4;this.light(g,f.x,f.y,70,'#ff9a43',.6);for(let i=0;i<6;i++)g.fillRect(f.x+Math.sin(i*7+this.time)*25,f.y-((this.time*40+i*6)%30),4,7);}else if(f.type==='spark'||f.type==='death'){let n=f.type==='death'?15:7;for(let i=0;i<n;i++){let a=i/n*Math.PI*2,r=(f.radius||35)*p;g.fillRect(f.x+Math.cos(a)*r,f.y-20+Math.sin(a)*r*.6-p*10,3,3);}}else if(f.type==='afterimage'){g.globalAlpha=.15*f.life/.18;this.player(g,{...this.game.p,x:f.x,y:f.y,invuln:0},this.game.state,94,this.time);}g.restore();}
 draw(dt=0){if(!this.ready)return;this.time+=dt;const {game,ctx:g,canvas,size:s,camera:c}=this;let tx=game.p.x-s.w/2,ty=game.p.y-s.h*.53;c.x+=(tx-c.x)*Math.min(1,dt*9);c.y+=(ty-c.y)*Math.min(1,dt*9);c.x=Math.max(0,Math.min(game.world.w-s.w,c.x));c.y=Math.max(0,Math.min(game.world.h-s.h,c.y));g.setTransform(this.dpr*s.z,0,0,this.dpr*s.z,0,0);g.imageSmoothingEnabled=false;g.fillStyle='#071215';g.fillRect(0,0,s.w,s.h);g.save();g.translate(-Math.round(c.x)+(Math.random()-.5)*this.shake,-Math.round(c.y)+(Math.random()-.5)*this.shake);this.shake*=.84;this.ground(g);
 const visible=(o,margin=240)=>o.x>c.x-margin&&o.x<c.x+s.w+margin&&o.y>c.y-20&&o.y<c.y+s.h+margin;
 for(const l of game.world.lights)if(visible(l,350))this.light(g,l.x,l.y,l.r*(1+Math.sin(this.time*3+l.x)*.025),l.color,.25);
 if(game.mode==='wilds')for(const e of game.enemies)if(visible(e))this.telegraph(g,e);
 const things=game.world.props.filter(o=>visible(o)).map(o=>({kind:'prop',...o}));for(const n of game.world.nodes){if(!visible(n)||!game.available(n)||n.type==='building'||n.type==='camp'&&game.mode!=='wilds')continue;if(n.sprite!==undefined)things.push({kind:'node',...n});}
 if(game.mode==='wilds'){things.push(...game.enemies.filter(e=>visible(e)).map(e=>({kind:'enemy',...e,ref:e})));for(const d of game.drops){let col=d.type==='item'?COLORS[RARITIES[ITEMS_SAFE(d.def).rarity]]:'#efc479';this.light(g,d.x,d.y,50,col,.45);g.strokeStyle=col;g.lineWidth=1.5;g.beginPath();g.moveTo(d.x,d.y-50);g.lineTo(d.x,d.y);g.stroke();if(d.type==='item')this.sprite(g,'actors',ITEMS_SAFE(d.def).sprite??22,d.x,d.y,34);else{g.fillStyle=col;g.fillRect(d.x-3,d.y-6,6,6);}}if(game.state.companion)things.push({kind:'companion',x:game.companion.x,y:game.companion.y});}
 if(game.peers&&game.mode==='clan')for(const peer of game.peers)things.push({kind:'peer',...peer});things.push({kind:'player',x:game.p.x,y:game.p.y});things.sort((a,b)=>a.y-b.y);
 for(const o of things){if(o.kind==='player'){this.player(g,game.p,game.state,94,this.time);continue;}if(o.kind==='enemy'){this.enemy(g,o.ref);continue;}if(o.kind==='peer'){this.player(g,{...o,moving:o.moving,invuln:0},o.state||game.state,94,this.time);g.font='12px system-ui';g.textAlign='center';g.fillStyle=o.offline?'#9aa8af':'#a8eee7';g.fillText(o.name+(o.offline?' · resting':''),o.x,o.y-95);if(o.emote&&this.time-o.emoteAt<3){g.font='24px serif';g.fillText(o.emote,o.x,o.y-115);}continue;}if(o.kind==='companion'){this.shadow(g,o.x,o.y,22);this.sprite(g,'actors',game.state.companion==='fox'?17:2,o.x,o.y+Math.sin(this.time*8)*2,game.state.companion==='fox'?62:80);this.light(g,o.x,o.y-20,70,'#44cfeb',.13);continue;}
 const set=o.actorSprite!==undefined||o.actor?'actors':'props',index=o.actorSprite??o.sprite;let size=o.size||(o.type==='deep'?150:o.type==='rift'?145:o.type==='wood'||o.type==='stone'?56:o.type==='rescue'?85:o.type==='fox'?65:o.type==='chest'?74:o.type==='shrine'?115:80);let alpha=1;if(o.kind==='prop'&&o.sprite<3&&Math.abs(o.x-game.p.x)<size*.35&&game.p.y<o.y&&game.p.y>o.y-size*.7)alpha=.38;this.shadow(g,o.x,o.y,size*.22);this.sprite(g,set,index,o.x,o.y,size,o.flip,alpha);if(o.type==='deep'||o.type==='rift')this.light(g,o.x,o.y-50,130,'#ae68ff',.16);if(o.actorSprite===13||o.type==='camp'){this.light(g,o.x,o.y-25,85,'#ffa14b',.32);if(game.state.settings.particles)for(let i=0;i<6;i++){g.fillStyle=i%2?'#ffc983':'#ffb463';g.globalAlpha=1-((this.time+i*.21)%1);g.fillRect(o.x+Math.sin(this.time+i*7)*16,o.y-30-((this.time*40+i*12)%80),2,3);g.globalAlpha=1;}}}
 if(game.mode!=='wilds'){for(const n of game.world.nodes.filter(n=>n.type==='building')){if(!n.built){g.strokeStyle='#c8ae7655';g.setLineDash([4,6]);g.strokeRect(n.x-40,n.y-45,80,42);g.setLineDash([]);}if(Math.hypot(n.x-game.p.x,n.y-game.p.y)<220){g.fillStyle=n.built?'#d3c5a2':'#9aa8a5';g.font='12px system-ui';g.textAlign='center';g.fillText(n.label,n.x,n.y+10);}}}
 for(const p of game.projectiles){g.fillStyle=p.color;g.shadowColor=p.color;g.shadowBlur=10;g.beginPath();g.arc(p.x,p.y,p.radius,0,Math.PI*2);g.fill();g.shadowBlur=0;g.strokeStyle=p.color;g.globalAlpha=.5;g.beginPath();g.moveTo(p.x,p.y);g.lineTo(p.x-p.vx*.045,p.y-p.vy*.045);g.stroke();g.globalAlpha=1;}
 for(const f of game.effects)this.drawEffect(g,f);
 const near=game.nearestNode();if(near){g.strokeStyle='#e5c890';g.lineWidth=1.4;g.beginPath();g.ellipse(near.x,near.y+5,34,12,0,0,Math.PI*2);g.stroke();}
 // Moon haze and drifting motes remain inexpensive at phone resolutions.
 if(game.state.settings.particles){for(let i=0;i<26;i++){let x=c.x+(i*173+this.time*(i%2?3:-3))%s.w,y=c.y+(i*109+this.time*4)%s.h;g.fillStyle=i%4?'#acd9cf':'#b9c7ff';g.globalAlpha=.12+.25*Math.abs(Math.sin(this.time+i));g.fillRect(x,y,2,2);}g.globalAlpha=1;}
 const hue=game.world.realm.hue;if(hue){g.globalCompositeOperation='color';g.globalAlpha=.22;g.fillStyle=hue===145?'#9dbbe9':hue===255?'#ae4430':hue===65?'#8046b8':'#325c45';g.fillRect(c.x,c.y,s.w,s.h);g.globalAlpha=1;g.globalCompositeOperation='source-over';}g.restore();
 g.save();g.imageSmoothingEnabled=true;const v=g.createRadialGradient(s.w/2,s.h*.52,s.w*.12,s.w/2,s.h*.52,Math.max(s.w,s.h)*.72);v.addColorStop(0,'#01081100');v.addColorStop(.6,'#010a1420');v.addColorStop(1,'#01080dc9');g.fillStyle=v;g.fillRect(0,0,s.w,s.h);g.restore();
 }
 minimap(canvas,large=false,world=this.game.world){const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,isFort=world.seed===0;const bounds=isFort?{x:430,y:790,w:1170,h:1060}:{x:200,y:170,w:1600,h:2980};const scale=Math.min((w-(large?48:12))/bounds.w,(h-(large?110:12))/bounds.h),ox=(w-bounds.w*scale)/2-bounds.x*scale,oy=(h-bounds.h*scale)/2-bounds.y*scale;
 g.clearRect(0,0,w,h);g.fillStyle='#0c1b20';g.fillRect(0,0,w,h);g.save();g.beginPath();g.rect(8,8,w-16,h-16);g.clip();g.globalAlpha=large?.5:.28;g.drawImage(this.images.ground,0,0,w,h);g.globalAlpha=1;g.save();g.translate(ox,oy);g.scale(scale,scale);g.fillStyle='#1b3030bb';g.fillRect(bounds.x,bounds.y,bounds.w,bounds.h);g.lineCap='round';g.lineJoin='round';
 for(const path of world.paths){g.beginPath();path.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.lineWidth=large?55:38;g.strokeStyle='#0a1417';g.stroke();g.lineWidth=large?28:15;g.strokeStyle='#998567';g.stroke();g.setLineDash([9,15]);g.strokeStyle='#dfc99999';g.lineWidth=8;g.stroke();g.setLineDash([]);}
 const props=world.props.filter(o=>o.x>bounds.x&&o.x<bounds.x+bounds.w);for(const o of props){g.globalAlpha=o.sprite<3?.72:.95;this.sprite(g,o.actorSprite!==undefined?'actors':'props',o.actorSprite??o.sprite,o.x,o.y,(o.size||90)*(large?1.2:1));}g.globalAlpha=1;
 if(large&&!isFort)for(const n of world.nodes.filter(n=>['shrine','rift','deep','chest'].includes(n.type)))this.sprite(g,n.actor?'actors':'props',n.sprite,n.x,n.y,140);
 g.restore();const label=(text,x,y,color='#d1d6bc',font=large?19:9)=>{g.font=`${font}px ${large?'Cinzel':'sans-serif'}`;g.textAlign='center';g.lineWidth=5;g.strokeStyle='#0b181df2';g.strokeText(text,x,y);g.fillStyle=color;g.fillText(text,x,y);};
 const rooms=isFort?world.nodes.filter(n=>n.type==='building').map(n=>({...n,name:({smith:'Blacksmith',quarters:'Quarters',farm:'Farms',workshop:'Workshop',barracks:'Barracks',forge:'Rift Forge',tower:'Mage Tower',pens:'Creature Pens'})[n.building],r:70})):world.rooms;
 for(const a of rooms){const seen=isFort||this.game.run.visited.includes(a.id)||a.id==='outpost',done=this.game.run.cleared.includes(a.id);const x=ox+a.x*scale,y=oy+a.y*scale;g.fillStyle=done?'#93b8a0':seen?'#dfbd7d':'#687d80';g.strokeStyle='#0c1c20';g.lineWidth=3;g.beginPath();g.arc(x,y,large?5:2.5,0,Math.PI*2);g.fill();g.stroke();if(large){const text=a.name;const yy=isFort?y+(a.building==='smith'?-18:a.building==='pens'?29:20):y+(a.id==='shrine'?-20:25);g.font='19px Cinzel';const half=g.measureText(text).width/2;label(text,Math.max(half+16,Math.min(w-half-16,x)),yy,seen?'#dfd6b4':'#889b96',isFort?16:19);}}
 const actualFort=this.game.mode!=='wilds',same=isFort===actualFort;const p=same?this.game.p:this.game.state.run||this.game.run;const px=ox+(p.x||1000)*scale,py=oy+(p.y||2990)*scale;if(same||!isFort){g.strokeStyle='#6be8e0';g.fillStyle='#c4fff4';g.lineWidth=1.5;g.beginPath();g.arc(px,py,large?10:4,0,Math.PI*2);g.stroke();g.beginPath();g.arc(px,py,large?4:2,0,Math.PI*2);g.fill();if(large)label(same?'YOU':'LAST CAMP',px,py-17,'#8ce8dd',12);}
 const target=same?this.game.objective().target:null;if(target){g.strokeStyle='#e3bd75';g.lineWidth=2;g.setLineDash(large?[3,4]:[]);g.beginPath();g.arc(ox+target.x*scale,oy+target.y*scale,large?15:6,0,Math.PI*2);g.stroke();g.setLineDash([]);}
 g.restore();if(large){g.strokeStyle='#9a8d5966';g.lineWidth=1;g.strokeRect(7,7,w-14,h-14);g.strokeRect(13,13,w-26,h-26);label(isFort?'EMBERHOLD':world.realm.name.toUpperCase(),w/2,39,'#ddc18b',22);label(isFort?'A FIRE WORTH RETURNING TO':'THE OLD KING’S ROAD  ·  DEPTH '+this.game.state.depth,w/2,h-25,'#8caaa1',11);g.save();g.translate(w-40,77);g.strokeStyle='#d1b782';g.beginPath();g.moveTo(0,-13);g.lineTo(-7,9);g.lineTo(0,4);g.lineTo(7,9);g.closePath();g.stroke();label('N',0,-20,'#d1b782',11);g.restore();}
 }

}
import {ITEMS} from './data.js?v=060';
const ITEMS_SAFE=id=>ITEMS[id]||ITEMS.rust;
