import {PRESETS,COLORS,RARITIES,SKINS,HAIRS,equipment,stats,realmFor} from './data.js';
export class Renderer{
 constructor(game,canvas){this.game=game;this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.images={};this.frames={};this.camera={x:0,y:0};this.avatarCache=new Map();this.ready=false;this.shake=0;this.time=0;this.size={w:100,h:100,z:1};game.on('hurt',()=>{if(game.state.settings.shake)this.shake=5;});game.on('burst',()=>{if(game.state.settings.shake)this.shake=7;});game.on('change',()=>this.avatarCache.clear());game.on('depth',()=>this.snap());game.on('mode',()=>this.snap());}
 async load(){await Promise.all(['actors','props','ground'].map(key=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{this.images[key]=im;resolve();};im.onerror=()=>reject(new Error('Could not load '+key+' artwork'));im.src='./assets/'+key+'.webp';})));for(const key of ['actors','props']){this.frames[key]=[];for(let i=0;i<24;i++){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.drawImage(this.images[key],i%6*256,Math.floor(i/6)*256,256,256,0,0,256,256);this.frames[key].push(c);}}this.ready=true;this.snap();}
 resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.dpr=dpr;let z=r.width<600?r.width/465:Math.min(1.1,r.height/740+.12);this.size={w:r.width/z,h:r.height/z,z};this.snap();}
 snap(){this.camera.x=this.game.p.x-this.size.w/2;this.camera.y=this.game.p.y-this.size.h*.53;}
 sprite(g,set,index,x,y,size=90,flip=false,alpha=1,angle=0){const c=this.frames[set]?.[index];if(!c)return;g.save();g.globalAlpha=alpha;g.translate(Math.round(x),Math.round(y));if(flip)g.scale(-1,1);if(angle)g.rotate(angle);g.drawImage(c,-size/2,-size*.9,size,size);g.restore();}
 avatar(s){const eq=equipment(s),key=[s.preset,s.skin,s.hair,s.body,...Object.values(eq).map(i=>i?.def)].join(',');if(this.avatarCache.has(key))return this.avatarCache.get(key);const c=document.createElement('canvas');c.width=180;c.height=220;const g=c.getContext('2d');g.imageSmoothingEnabled=false;let preset=PRESETS.findIndex(p=>p.id===s.preset);let look=eq.chest?.look;if(eq.chest?.def!=='coat'&&look!==undefined)preset=look;
 const base=this.frames.actors?.[Math.max(0,preset)];if(!base)return c;let bodyW=s.body?145:132;g.drawImage(base,(180-bodyW)/2,22,bodyW,166);
 // Palette changes only affect existing opaque pixels in the body sprite.
 const pixels=g.getImageData(0,0,180,220),data=pixels.data,skin=SKINS[s.skin||0],hair=HAIRS[s.hair||0];const rgb=h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];const srgb=rgb(skin),hrgb=rgb(hair);
 for(let y=35;y<180;y++)for(let x=28;x<154;x++){let j=(y*180+x)*4,r=data[j],b=data[j+2],green=data[j+1];if(data[j+3]<180)continue;if(y<78&&x>63&&x<121&&r>green*1.12&&green>b*1.12&&r>65){let l=(r+green+b)/500;for(let k=0;k<3;k++)data[j+k]=Math.min(255,srgb[k]*l);}if(preset===4&&y<52&&x>70&&x<108&&r<90&&green<70&&b<75){let l=(r+green+b)/150+.4;for(let k=0;k<3;k++)data[j+k]=Math.min(255,hrgb[k]*l);}
 const tint= y>156?eq.boots:y>101&&y<132&&(x<66||x>116)?eq.gloves:null;if(tint&&tint.rarity>0){const color=rgb(COLORS[RARITIES[tint.rarity]]);for(let k=0;k<3;k++)data[j+k]=data[j+k]*.5+color[k]*.42;}}
 g.putImageData(pixels,0,0);if(eq.helmet?.sprite!==undefined){this.sprite(g,'actors',eq.helmet.sprite,92,81,51);}if(eq.cloak){g.save();g.globalCompositeOperation='source-atop';g.globalAlpha=.23;g.fillStyle=eq.cloak.rarity>=3?'#a45cef':'#20b1b7';g.fillRect(22,71,40,103);g.restore();}if(eq.shield){g.save();g.translate(50,124);g.strokeStyle=eq.shield.rarity>=3?'#7feaf2':'#849496';g.fillStyle='#293542';g.lineWidth=3;g.beginPath();g.moveTo(-14,-18);g.lineTo(14,-18);g.lineTo(12,5);g.lineTo(0,18);g.lineTo(-12,5);g.closePath();g.fill();g.stroke();g.strokeStyle='#ad965d';g.beginPath();g.moveTo(0,-12);g.lineTo(0,9);g.stroke();g.restore();}this.avatarCache.set(key,c);return c;}
 player(g,p,s,size=94,time=0){const eq=equipment(s),a=this.avatar(s),bob=p.moving?Math.sin(time*14)*2:Math.sin(time*2)*.6;this.shadow(g,p.x,p.y,36);g.save();g.translate(p.x,p.y+bob);if(p.face<0)g.scale(-1,1);const rarity=eq.chest?.rarity||eq.weapon?.rarity||0;if(rarity>=3){g.shadowColor=COLORS[RARITIES[rarity]];g.shadowBlur=10;}if(p.invuln>0&&Math.floor(time*18)%2===0)g.globalAlpha=.55;g.drawImage(a,-size*.46,-size*.9,size*.9,size*1.1);g.shadowBlur=0;const w=eq.weapon;if(w){g.save();g.translate(23,-size*.38);g.rotate(p.swing>0?-1.3+p.swing*7:.6);this.sprite(g,'actors',w.sprite,0,20,w.kind==='greatsword'?67:w.kind==='staff'?68:55,false,1);g.restore();}g.restore();if(p.ward>0){g.strokeStyle='#75dff8';g.lineWidth=1.5;g.beginPath();g.ellipse(p.x,p.y-33,34,45,0,0,Math.PI*2);g.stroke();}}
 shadow(g,x,y,r=30){g.save();g.globalAlpha=.27;g.fillStyle='#000';g.beginPath();g.ellipse(x,y+2,r,r*.29,0,0,Math.PI*2);g.fill();g.restore();}
 light(g,x,y,r,color,alpha=.25){g.save();g.globalAlpha=alpha;g.globalCompositeOperation='screen';const grad=g.createRadialGradient(x,y,0,x,y,r);grad.addColorStop(0,color);grad.addColorStop(.35,color+'66');grad.addColorStop(1,color+'00');g.fillStyle=grad;g.fillRect(x-r,y-r,r*2,r*2);g.restore();}
 ground(g){const {camera:c,size:s,game}=this;g.fillStyle='#152420';g.fillRect(c.x,c.y,s.w,s.h);const tile=512,startX=Math.floor(c.x/tile)*tile,startY=Math.floor(c.y/tile)*tile;for(let x=startX;x<c.x+s.w;x+=tile)for(let y=startY;y<c.y+s.h;y+=tile)g.drawImage(this.images.ground,x,y,tile,tile);g.fillStyle='#060f13';g.globalAlpha=.35;g.fillRect(c.x,c.y,s.w,s.h);g.globalAlpha=1;
 g.lineCap='round';g.lineJoin='round';for(const path of game.world.paths){g.beginPath();path.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.strokeStyle='#172624';g.lineWidth=126;g.stroke();g.strokeStyle='#2f3431';g.lineWidth=85;g.stroke();g.strokeStyle='#3b3c34';g.lineWidth=64;g.globalAlpha=.4;g.stroke();g.globalAlpha=1;
 for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],d=Math.hypot(b[0]-a[0],b[1]-a[1]);for(let j=0;j<d;j+=27){let t=j/d,x=a[0]+(b[0]-a[0])*t,y=a[1]+(b[1]-a[1])*t;if(x<c.x-80||y<c.y-80||x>c.x+s.w+80||y>c.y+s.h+80)continue;for(let k=-1;k<=1;k++){let seed=(j*31+i*79+k*17)%20;g.fillStyle=(j+k)%3===0?'#54544777':'#68706333';g.fillRect(Math.floor(x+k*24+seed/3)-8,Math.floor(y)-7,16+seed%8,12);}}}}
 if(game.mode==='wilds'){for(const a of game.world.rooms){if(a.id==='grove'){g.strokeStyle='#86788a55';g.lineWidth=5;g.beginPath();g.ellipse(a.x,a.y,256,218,0,0,Math.PI*2);g.stroke();}if(a.id==='scar'){g.save();g.translate(a.x,a.y);g.strokeStyle='#b268dd66';g.lineWidth=3;for(let i=0;i<8;i++){g.rotate(Math.PI/4);g.beginPath();g.moveTo(20,0);g.lineTo(72,-24);g.lineTo(91,13);g.lineTo(172,-8);g.stroke();}g.restore();}}}
 }
 enemy(g,e){this.shadow(g,e.x,e.y,e.type==='boss'?75:e.type==='wolf'||e.type==='alpha'?35:27);g.save();if(e.elite||e.type==='boss'){g.shadowColor=e.type==='boss'?'#48ccf3':'#aa55ee';g.shadowBlur=e.type==='boss'?16:8;}if(e.flash>0)g.filter='brightness(2)';let size=e.type==='boss'?205:e.type==='brute'?112:e.type==='wolf'||e.type==='alpha'?95:88;this.sprite(g,'actors',e.sprite,e.x,e.y+Math.sin(this.time*7+e.id)*1.2,size,e.face<0);g.restore();if(e.type!=='boss'&&(e.hp<e.max||e.elite)){const w=e.elite?54:40;g.fillStyle='#0c1720';g.fillRect(e.x-w/2,e.y-size*.9-9,w,4);g.fillStyle=e.elite?'#c591f6':'#b96467';g.fillRect(e.x-w/2,e.y-size*.9-9,w*e.hp/e.max,4);}if(e.elite){g.fillStyle='#dfb7ff';g.font='11px sans-serif';g.textAlign='center';g.fillText('ELITE',e.x,e.y-size*.9-16);}}
 telegraph(g,e){if(e.windup<=0)return;const p=1-e.windup/e.windupMax;g.save();g.strokeStyle='#ff958c';g.fillStyle='#e4596035';g.lineWidth=2;if(e.type==='boss'&&e.attack==='charge'){let a=Math.atan2(e.ty-e.y,e.tx-e.x);g.translate(e.x,e.y);g.rotate(a);g.fillRect(0,-28,340,56);g.strokeRect(0,-28,340,56);g.fillStyle='#ffc2b4';g.globalAlpha=.2+p*.3;g.fillRect(0,-28,340*p,56);}else if(e.type==='boss'&&e.attack==='wave'){g.beginPath();g.arc(e.x,e.y,250,0,Math.PI*2);g.fill();g.stroke();g.beginPath();g.arc(e.x,e.y,250*p,0,Math.PI*2);g.stroke();}else if(e.type==='archer'){g.setLineDash([7,7]);g.beginPath();g.moveTo(e.x,e.y-20);g.lineTo(e.tx,e.ty-20);g.stroke();}else{const radius=e.type==='brute'?85:e.type==='boss'?115:55;const x=e.type==='brute'?e.tx:e.x,y=e.type==='brute'?e.ty:e.y;g.beginPath();g.ellipse(x,y,radius,radius*.7,0,0,Math.PI*2);g.fill();g.stroke();g.strokeStyle='#ffc0ba';g.beginPath();g.ellipse(x,y,radius,radius*.7,0,-Math.PI/2,-Math.PI/2+Math.PI*2*p);g.stroke();}g.restore();}
 drawEffect(g,f){const p=1-f.life/f.maxLife;g.save();g.globalAlpha=Math.min(1,f.life*3);g.strokeStyle=f.color||'#7edce9';g.fillStyle=f.color||'#7edce9';if(f.type==='text'){g.font='600 17px system-ui';g.textAlign='center';g.shadowColor='#050b0f';g.shadowBlur=4;g.fillText(f.text,f.x,f.y-p*35);}else if(f.type==='ring'||f.type==='shockwave'){g.lineWidth=(1-p)*5+1;g.beginPath();g.ellipse(f.x,f.y,(f.radius||100)*p,(f.radius||100)*p*.7,0,0,Math.PI*2);g.stroke();this.light(g,f.x,f.y,(f.radius||100)*p+20,f.color,.12*(1-p));}else if(f.type==='slash'){g.translate(f.x,f.y-20);if(f.face<0)g.scale(-1,1);g.lineWidth=(1-p)*10+1;g.beginPath();g.arc(0,0,f.radius*.72,-1.6+p,1.4+p);g.stroke();}else if(f.type==='trail'){g.globalAlpha=.4;this.light(g,f.x,f.y,70,'#ff9a43',.6);for(let i=0;i<6;i++)g.fillRect(f.x+Math.sin(i*7+this.time)*25,f.y-((this.time*40+i*6)%30),4,7);}else if(f.type==='spark'||f.type==='death'){let n=f.type==='death'?15:7;for(let i=0;i<n;i++){let a=i/n*Math.PI*2,r=(f.radius||35)*p;g.fillRect(f.x+Math.cos(a)*r,f.y-20+Math.sin(a)*r*.6-p*10,3,3);}}else if(f.type==='afterimage'){g.globalAlpha=.15*f.life/.18;this.player(g,{...this.game.p,x:f.x,y:f.y,invuln:0},this.game.state,94,this.time);}g.restore();}
 draw(dt=0){if(!this.ready)return;this.time+=dt;const {game,ctx:g,canvas,size:s,camera:c}=this;let tx=game.p.x-s.w/2,ty=game.p.y-s.h*.53;c.x+=(tx-c.x)*Math.min(1,dt*9);c.y+=(ty-c.y)*Math.min(1,dt*9);c.x=Math.max(0,Math.min(game.world.w-s.w,c.x));c.y=Math.max(0,Math.min(game.world.h-s.h,c.y));g.setTransform(this.dpr*s.z,0,0,this.dpr*s.z,0,0);g.imageSmoothingEnabled=false;g.fillStyle='#071215';g.fillRect(0,0,s.w,s.h);g.save();g.translate(-Math.round(c.x)+(Math.random()-.5)*this.shake,-Math.round(c.y)+(Math.random()-.5)*this.shake);this.shake*=.84;this.ground(g);
 const visible=(o,margin=240)=>o.x>c.x-margin&&o.x<c.x+s.w+margin&&o.y>c.y-20&&o.y<c.y+s.h+margin;
 for(const l of game.world.lights)if(visible(l,350))this.light(g,l.x,l.y,l.r*(1+Math.sin(this.time*3+l.x)*.025),l.color,.25);
 if(game.mode==='wilds')for(const e of game.enemies)if(visible(e))this.telegraph(g,e);
 const things=game.world.props.filter(o=>visible(o)).map(o=>({kind:'prop',...o}));for(const n of game.world.nodes){if(!visible(n)||!game.available(n)||n.type==='building'||n.type==='camp'&&game.mode!=='wilds')continue;if(n.sprite!==undefined)things.push({kind:'node',...n});}
 if(game.mode==='wilds'){things.push(...game.enemies.filter(e=>visible(e)).map(e=>({kind:'enemy',...e,ref:e})));for(const d of game.drops){let col=d.type==='item'?COLORS[RARITIES[ITEMS_SAFE(d.def).rarity]]:'#efc479';this.light(g,d.x,d.y,50,col,.45);g.strokeStyle=col;g.lineWidth=1.5;g.beginPath();g.moveTo(d.x,d.y-50);g.lineTo(d.x,d.y);g.stroke();if(d.type==='item')this.sprite(g,'actors',ITEMS_SAFE(d.def).sprite??22,d.x,d.y,34);else{g.fillStyle=col;g.fillRect(d.x-3,d.y-6,6,6);}}if(game.state.companion)things.push({kind:'companion',x:game.companion.x,y:game.companion.y});}
 if(game.peers&&game.mode==='clan')for(const peer of game.peers)things.push({kind:'peer',...peer});things.push({kind:'player',x:game.p.x,y:game.p.y});things.sort((a,b)=>a.y-b.y);
 for(const o of things){if(o.kind==='player'){this.player(g,game.p,game.state,94,this.time);continue;}if(o.kind==='enemy'){this.enemy(g,o.ref);continue;}if(o.kind==='peer'){this.player(g,{...o,moving:o.moving,invuln:0},o.state||game.state,94,this.time);g.font='12px system-ui';g.textAlign='center';g.fillStyle=o.offline?'#9aa8af':'#a8eee7';g.fillText(o.name+(o.offline?' · resting':''),o.x,o.y-95);if(o.emote&&this.time-o.emoteAt<3){g.font='24px serif';g.fillText(o.emote,o.x,o.y-115);}continue;}if(o.kind==='companion'){this.shadow(g,o.x,o.y,22);this.sprite(g,'actors',game.state.companion==='fox'?17:2,o.x,o.y+Math.sin(this.time*8)*2,game.state.companion==='fox'?62:80);this.light(g,o.x,o.y-20,70,'#44cfeb',.13);continue;}
 const set=o.actorSprite!==undefined||o.actor?'actors':'props',index=o.actorSprite??o.sprite;let size=o.size||(o.type==='deep'?150:o.type==='rift'?145:o.type==='wood'||o.type==='stone'?56:o.type==='rescue'?85:o.type==='fox'?65:o.type==='chest'?74:o.type==='shrine'?115:80);let alpha=1;if(o.kind==='prop'&&o.sprite<3&&Math.abs(o.x-game.p.x)<size*.35&&game.p.y<o.y&&game.p.y>o.y-size*.7)alpha=.38;this.shadow(g,o.x,o.y,size*.22);this.sprite(g,set,index,o.x,o.y,size,o.flip,alpha);if(o.type==='deep'||o.type==='rift')this.light(g,o.x,o.y-50,130,'#ae68ff',.16);if(o.actorSprite===13||o.type==='camp'){this.light(g,o.x,o.y-25,85,'#ffa14b',.32);if(game.state.settings.particles)for(let i=0;i<6;i++){g.fillStyle=i%2?'#ffc983':'#ffb463';g.globalAlpha=1-((this.time+i*.21)%1);g.fillRect(o.x+Math.sin(this.time+i*7)*16,o.y-30-((this.time*40+i*12)%80),2,3);g.globalAlpha=1;}}}
 if(game.mode!=='wilds'){for(const n of game.world.nodes.filter(n=>n.type==='building')){if(!n.built){g.strokeStyle='#c8ae7655';g.setLineDash([4,6]);g.strokeRect(n.x-40,n.y-45,80,42);g.setLineDash([]);}if(Math.hypot(n.x-game.p.x,n.y-game.p.y)<220){g.fillStyle=n.built?'#d3c5a2':'#9aa8a5';g.font='12px system-ui';g.textAlign='center';g.fillText(n.label,n.x,n.y+10);}}}
 for(const p of game.projectiles){g.fillStyle=p.color;g.shadowColor=p.color;g.shadowBlur=10;g.beginPath();g.arc(p.x,p.y,p.radius,0,Math.PI*2);g.fill();g.shadowBlur=0;g.strokeStyle=p.color;g.globalAlpha=.5;g.beginPath();g.moveTo(p.x,p.y);g.lineTo(p.x-p.vx*.045,p.y-p.vy*.045);g.stroke();g.globalAlpha=1;}
 for(const f of game.effects)this.drawEffect(g,f);
 const near=game.nearestNode();if(near){g.strokeStyle='#e5c890';g.lineWidth=1.4;g.beginPath();g.ellipse(near.x,near.y+5,34,12,0,0,Math.PI*2);g.stroke();}
 // Moon haze and drifting motes remain inexpensive at phone resolutions.
 if(game.state.settings.particles){for(let i=0;i<26;i++){let x=c.x+(i*173+this.time*(i%2?3:-3))%s.w,y=c.y+(i*109+this.time*4)%s.h;g.fillStyle=i%4?'#acd9cf':'#b9c7ff';g.globalAlpha=.12+.25*Math.abs(Math.sin(this.time+i));g.fillRect(x,y,2,2);}g.globalAlpha=1;}
 const hue=game.world.realm.hue;if(hue){g.globalCompositeOperation='color';g.globalAlpha=.22;g.fillStyle=hue===145?'#9dbbe9':hue===255?'#ae4430':hue===65?'#8046b8':'#325c45';g.fillRect(c.x,c.y,s.w,s.h);g.globalAlpha=1;g.globalCompositeOperation='source-over';}g.restore();
 g.save();g.imageSmoothingEnabled=true;const v=g.createRadialGradient(s.w/2,s.h*.52,s.w*.12,s.w/2,s.h*.52,Math.max(s.w,s.h)*.72);v.addColorStop(0,'#01081100');v.addColorStop(.6,'#010a1420');v.addColorStop(1,'#01080dc9');g.fillStyle=v;g.fillRect(0,0,s.w,s.h);g.restore();
 }
 minimap(canvas,large=false){const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,world=this.game.world,s=Math.min((w-20)/world.w,(h-20)/world.h),ox=(w-world.w*s)/2,oy=(h-world.h*s)/2;g.clearRect(0,0,w,h);g.fillStyle='#0b171ccc';g.fillRect(0,0,w,h);g.strokeStyle='#83988a66';g.lineWidth=large?4:2;for(const path of world.paths){g.beginPath();path.forEach((p,i)=>i?g.lineTo(ox+p[0]*s,oy+p[1]*s):g.moveTo(ox+p[0]*s,oy+p[1]*s));g.stroke();}for(const a of world.rooms){const seen=this.game.run.visited.includes(a.id)||a.id==='outpost'||this.game.mode!=='wilds';g.fillStyle=this.game.run.cleared.includes(a.id)?'#778a70':seen?'#c9a565':'#6e7f834d';g.beginPath();g.arc(ox+a.x*s,oy+a.y*s,large?6:3,0,Math.PI*2);g.fill();if(large){g.fillStyle=seen?'#d9dfd7':'#718385';g.font='13px system-ui';g.textAlign='center';g.fillText(a.name,ox+a.x*s,oy+a.y*s+21);}}const target=this.game.objective().target;if(target){g.strokeStyle='#e3bd75';g.lineWidth=1;g.beginPath();g.arc(ox+target.x*s,oy+target.y*s,large?11:6,0,Math.PI*2);g.stroke();}g.fillStyle='#76e6e0';g.beginPath();g.arc(ox+this.game.p.x*s,oy+this.game.p.y*s,large?5:3,0,Math.PI*2);g.fill();}
}
import {ITEMS} from './data.js';
const ITEMS_SAFE=id=>ITEMS[id]||ITEMS.rust;
