(()=>{
S.preset=S.preset||'wanderer';
const SPR=window.SHATTER_SPRITES, atlas=new Image();let atlasReady=false,playerFacing=1;
atlas.onload=()=>{atlasReady=true;renderDoll();renderPresets();renderClanSprites()};atlas.src=SPR.src;
function atlasDraw(g,name,cx,cy,w,h,flip=false,alpha=1){if(!atlasReady||!SPR.map[name])return false;const [sx,sy]=SPR.map[name];g.save();g.globalAlpha=alpha;g.imageSmoothingEnabled=false;g.translate(cx,cy);if(flip)g.scale(-1,1);g.drawImage(atlas,sx,sy,SPR.cell,SPR.cell,-w/2,-h/2,w,h);g.restore();return true}
function shadow(g,x,y,w=42){g.save();g.globalAlpha=.38;g.fillStyle='#000';g.beginPath();g.ellipse(x,y+20,w/2,8,0,0,Math.PI*2);g.fill();g.restore()}
const oldPlayer=drawPlayerSprite,oldWolf=drawWolf,oldBandit=drawBandit,oldWretch=drawWretch,oldStag=drawStag,oldPOIs=drawPOIs,oldDoll=renderDoll;
drawPlayerSprite=function(g,x,y,s=2,dir=0,walk=0){if(!atlasReady)return oldPlayer(g,x,y,s,dir,walk);const bob=walk?Math.sin(performance.now()/85)*1.5:0;shadow(g,x,y,46);atlasDraw(g,'player_'+(S.preset||'wanderer'),x,y-17+bob,91,91,playerFacing<0);const wc=colorWeapon();g.save();g.shadowColor=wc;g.shadowBlur=rank(find(S.eq.weapon)?.rarity||'common')>=2?8:0;g.strokeStyle=wc;g.lineWidth=3;g.beginPath();if(playerFacing<0){g.moveTo(x-17,y-8);g.lineTo(x-37,y+11)}else{g.moveTo(x+17,y-8);g.lineTo(x+37,y+11)}g.stroke();g.restore();if(rank(find(S.eq.chest)?.rarity||'common')>=3){g.save();g.globalAlpha=.18;g.fillStyle=colorArmor();g.beginPath();g.arc(x,y-8,31,0,Math.PI*2);g.fill();g.restore()}};
drawWolf=function(g,e,sx,sy,t){if(!atlasReady)return oldWolf(g,e,sx,sy,t);shadow(g,sx,sy,55);let n=e.enc==='rift'?'wolf_rift':e.elite?'wolf_alpha':'wolf_gloom';atlasDraw(g,n,sx,sy-15+Math.sin(t/105+e.x)*1.2,104,82,e.dir<0)};
drawBandit=function(g,e,sx,sy){if(!atlasReady)return oldBandit(g,e,sx,sy);shadow(g,sx,sy,46);let n;if(e.elite)n='bandit_elite';else{const v=Math.abs(Math.floor(e.x/37))%3;n=['bandit_sword','bandit_hatchet','bandit_archer'][v]}atlasDraw(g,n,sx,sy-24,e.elite?96:82,e.elite?106:96,e.dir<0)};
drawWretch=function(g,e,sx,sy,t){if(!atlasReady)return oldWretch(g,e,sx,sy,t);shadow(g,sx,sy,48);const n=e.elite?'rift_brute':((Math.abs(Math.floor(e.x/41))%3===1)?'rift_stalker':'rift_wretch');g.save();g.shadowColor='#9a58ff';g.shadowBlur=9;atlasDraw(g,n,sx,sy-24+Math.sin(t/150+e.x)*2,n==='rift_brute'?100:86,n==='rift_brute'?112:100,e.dir<0);g.restore()};
drawStag=function(g,e,sx,sy,t){if(!atlasReady)return oldStag(g,e,sx,sy,t);shadow(g,sx,sy,120);g.save();g.shadowColor=e.hp/e.max<.3?'#effcff':'#67dcff';g.shadowBlur=18+Math.sin(t/120)*4;atlasDraw(g,'boss_hollow_stag',sx,sy-47,208,154,e.dir<0);g.restore()};
renderDoll=function(){const d=$('doll'),g=d.getContext('2d');g.imageSmoothingEnabled=false;g.clearRect(0,0,d.width,d.height);if(!atlasReady)return oldDoll();atlasDraw(g,'player_'+(S.preset||'wanderer'),d.width/2,d.height/2,105,105,false);let r=find(S.eq.weapon)?.rarity||'common';if(rank(r)>=2){g.save();g.strokeStyle=colorWeapon();g.shadowColor=colorWeapon();g.shadowBlur=9;g.lineWidth=3;g.beginPath();g.moveTo(60,48);g.lineTo(82,76);g.stroke();g.restore()}};
drawPOIs=function(t){oldPOIs(t);if(!atlasReady)return;function npc(name,wx,wy,w,h,alpha=1){let s=worldToScreen(wx,wy);if(s.x<-100||s.x>canvas.width+100||s.y<-120||s.y>canvas.height+120)return;shadow(ctx,s.x,s.y,42);atlasDraw(ctx,name,s.x,s.y-h*.28,w,h,false,alpha)}npc('npc_outpost_guard',1040,3260,76,82,.9);npc('npc_merchant',1235,3285,90,78,.9);npc('npc_shrine_spirit',540,2075,82,102,.94)};
const presetNames={wanderer:'WANDERER',knight:'KNIGHT',hunter:'HUNTER',acolyte:'ACOLYTE',blademaster:'BLADEMASTER',riftborn:'RIFTBORN'};
function renderPresets(){const host=$('presets');if(!host)return;host.innerHTML=Object.keys(presetNames).map(p=>`<button class="preset ${S.preset===p?'on':''}" data-preset="${p}"><canvas width="64" height="64"></canvas><span>${presetNames[p]}</span></button>`).join('');if(!atlasReady)return;host.querySelectorAll('.preset').forEach(b=>{const g=b.querySelector('canvas').getContext('2d');g.imageSmoothingEnabled=false;atlasDraw(g,'player_'+b.dataset.preset,32,32,62,62,false)})}
$('creator').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(!b)return;S.preset=b.dataset.preset;renderPresets();renderDoll()});
const originalOpen=openCreator;openCreator=function(){originalOpen();renderPresets()};$('customize').onclick=openCreator;
function clanCanvas(name,left,top,label,online){const yard=$('clanYard'),c=document.createElement('canvas');c.width=64;c.height=72;c.className='npc-sprite';c.style.left=left+'%';c.style.top=top+'%';c.dataset.sprite=name;yard.appendChild(c);let tag=document.createElement('div');tag.className='npc-tag'+(online?' online':'');tag.style.left=left+'%';tag.style.top=`calc(${top}% + 32px)`;tag.textContent=(online?'● ':'')+label;yard.appendChild(tag);return c}
function renderClanSprites(){const yard=$('clanYard');if(!yard||!atlasReady)return;yard.querySelectorAll('.npc-sprite,.npc-tag,.clanmate').forEach(n=>n.remove());[['player_blademaster',22,69,'Mara',1],['player_knight',73,67,'Kade',1],['player_hunter',31,35,'Rowan',1],['player_acolyte',68,35,'Elira',0],['npc_blacksmith',16,91,'Blacksmith',0],['npc_researcher',83,90,'Researcher',0],['npc_clan_elder',50,23,'Clan Elder',0]].forEach(v=>{let c=clanCanvas(...v);let g=c.getContext('2d');g.imageSmoothingEnabled=false;atlasDraw(g,v[0],32,35,62,62,false)})}
// True analog mobile joystick. Tap-to-move is intentionally disabled.
const joy=$('joystick'),knob=$('stick');let J={active:false,id:null,x:0,y:0,mag:0};
function moveStick(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.31;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy);if(d>max){dx*=max/d;dy*=max/d;d=max}let nx=dx/max,ny=dy/max,m=d/max;if(m<.12){nx=ny=m=0}J.x=nx;J.y=ny;J.mag=m;knob.style.transform=`translate(${dx}px,${dy}px)`;if(Math.abs(nx)>.12)playerFacing=nx<0?-1:1}
function endJoy(e){if(J.id!==null&&e.pointerId!==undefined&&e.pointerId!==J.id)return;J.active=false;J.id=null;J.x=J.y=J.mag=0;knob.style.transform='translate(0px,0px)';joy.classList.remove('active');P.targetX=P.x;P.targetY=P.y}
joy.addEventListener('pointerdown',e=>{e.preventDefault();J.active=true;J.id=e.pointerId;joy.setPointerCapture?.(e.pointerId);joy.classList.add('active');moveStick(e)});
joy.addEventListener('pointermove',e=>{if(!J.active||e.pointerId!==J.id)return;e.preventDefault();moveStick(e)});
joy.addEventListener('pointerup',endJoy);joy.addEventListener('pointercancel',endJoy);joy.addEventListener('lostpointercapture',endJoy);
canvas.addEventListener('pointerdown',e=>{e.preventDefault();e.stopImmediatePropagation()},true);
canvas.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation()},true);
(function drive(){if(J.active&&J.mag>.1){P.targetX=P.x+J.x*1200;P.targetY=P.y+J.y*1200;P.speed=190*(.38+.62*J.mag)}else{P.targetX=P.x;P.targetY=P.y;P.speed=190}requestAnimationFrame(drive)})();
renderPresets();
})();