import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {SAVE_KEY,stats,item,buildingCost,freshSave,safeSave} from '../data.js';
import {createWorld,FORT_POS} from '../world.js';
const storage=()=>{const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)}};
function game(){const g=new Game(storage());g.paused=false;g.state.created=true;return g;}
function frames(g,seconds){for(let i=0;i<seconds*60;i++)g.update(1/60);}
test('new player survives the opening encounter using real auto-attacks',()=>{const g=game();g.p.x=1000;g.p.y=2460;frames(g,25);assert.ok(g.run.cleared.includes('road'));assert.equal(g.state.kills,2);assert.ok(g.state.hp>0);assert.ok(g.drops.some(d=>d.def==='iron')||g.state.inventory.some(i=>i.def==='iron'));});
test('a pending encounter and position survive a save and reload',()=>{const g=game();g.p.x=1000;g.p.y=2470;frames(g,.1);g.enemies[0].hp=19;g.save();const next=new Game(g.storage);assert.equal(next.enemies.length,2);assert.equal(next.enemies[0].hp,19);assert.equal(next.p.x,g.p.x);assert.deepEqual(next.run.cleared,g.run.cleared);});
test('opening chest grants resources and visible equippable weapons only once',()=>{const g=game();const chest=g.world.nodes.find(n=>n.id==='chest');g.p.x=chest.x;g.p.y=chest.y+50;g.interact(chest);assert.equal(g.state.bag.gold,17);const bow=g.state.inventory.find(i=>i.def==='bow');assert.ok(bow);g.equip(bow.uid);assert.equal(stats(g.state).weapon,'bow');assert.equal(stats(g.state).range,260);assert.equal(g.available(chest),false);});
test('fortress upgrades spend resources once, change the world, and survive reload',()=>{const g=game();g.state.bag={gold:100,wood:100,stone:100,ember:5,food:0};g.enterFortress();const before=g.state.bank.gold,cost=buildingCost(g.state,'smith');assert.equal(g.build('smith'),true);assert.equal(g.state.bank.gold,before-cost.gold);assert.ok(g.world.props.some(p=>p.id==='smith'));assert.equal(g.state.fort.smith,1);g.leaveFortress();const reload=new Game(g.storage);assert.equal(reload.state.fort.smith,1);});
test('death retains equipped gear and depth, loses only carried resources, and respawns',()=>{const g=game();g.state.bank.gold=100;g.state.bag.gold=40;const eq={...g.state.equipment};g.state.hp=1;g.hurt(1000);assert.equal(g.state.bag.gold,36);assert.equal(g.state.bank.gold,100);assert.deepEqual(g.state.equipment,eq);assert.equal(g.state.depth,1);assert.equal(g.state.hp,stats(g.state).maxHp);assert.equal(g.p.y,2990);});
test('dodge gives brief invulnerability and cooldowns prevent repeated healing',()=>{const g=game();g.state.hp=30;g.ability('heal');const hp=g.state.hp;assert.equal(g.ability('heal'),false);assert.equal(g.state.hp,hp);g.ability('dodge');g.hurt(40);assert.equal(g.state.hp,hp);frames(g,1);assert.equal(g.p.invuln,0);});
test('boss telegraphs attacks, changes phase, summons, and opens the next depth',()=>{const g=game();g.run.cleared.push('scar');g.p.x=1000;g.p.y=600;frames(g,.1);let boss=g.enemies.find(e=>e.type==='boss');assert.ok(boss);boss.cooldown=0;frames(g,.02);assert.ok(boss.windup>0);assert.equal(boss.attack,'charge');boss.hp=boss.max*.3;frames(g,.02);assert.equal(boss.phase,2);assert.ok(g.enemies.some(e=>e.type==='stalker'));for(const e of g.enemies.slice())g.damageEnemy(e,10000);assert.ok(g.run.cleared.includes('grove'));assert.equal(g.state.bosses,1);g.descend();assert.equal(g.state.depth,2);assert.equal(g.run.cleared.length,0);assert.equal(g.state.bestDepth,2);assert.equal(g.state.bosses,1);});
test('maps are deterministic, change at depth, and later depths introduce stalkers',()=>{assert.deepEqual(createWorld(2),createWorld(2));assert.notDeepEqual(createWorld(1).props,createWorld(2).props);const g=game();g.state.depth=3;g.state.run=null;g.loadRun();g.p.x=1000;g.p.y=2470;frames(g,.1);assert.ok(g.enemies.some(e=>e.type==='stalker'));});
test('offline production caps at eight hours and cannot be claimed twice',()=>{const mem=storage(),s=freshSave();s.created=true;s.survivors=['smith'];s.fort={workshop:1,farm:1,quarters:1};s.lastSaved=Date.now()-24*3600000;mem.setItem(SAVE_KEY,JSON.stringify(s));const g=new Game(mem);assert.equal(g.state.bank.wood,40);assert.equal(g.state.bank.stone,24);assert.equal(g.state.bank.food,32);const second=new Game(mem);assert.equal(second.state.bank.wood,40);assert.equal(second.offline,null);});
test('legacy saves preserve player progress and owned equipment',()=>{const mem=storage();mem.setItem('shatterdeep-v03',JSON.stringify({created:true,name:'Veteran',depth:4,level:9,gold:120,stone:8,ember:3,inv:['rust','cinder','plate'],eq:{weapon:'cinder',chest:'plate'},fort:{smith:2}}));const g=new Game(mem);assert.equal(g.state.depth,4);assert.equal(g.state.level,9);assert.equal(g.state.bank.gold,120);assert.equal(g.state.equipment.weapon,'legacy-cinder');assert.equal(g.state.fort.smith,2);});
test('invalid inventory entries are filtered and an absent weapon is repaired',()=>{const s=safeSave({name:'Test',inventory:[{def:'not-real',uid:'x'}],equipment:{weapon:'x'},level:-3,depth:Infinity});assert.equal(s.level,1);assert.equal(s.depth,1);assert.equal(s.inventory[0].def,'rust');assert.ok(s.equipment.weapon);});

test('unequipping every slot persists without deleting items or restoring a weapon',()=>{const g=game(),count=g.state.inventory.length;for(const slot of ['weapon','chest','boots'])assert.equal(g.unequip(slot),true);const next=new Game(g.storage);assert.equal(next.state.inventory.length,count);assert.equal(next.state.equipment.weapon,null);assert.equal(stats(next.state).weapon,'unarmed');assert.equal(stats(next.state).armor,0);});
test('each construction relocates an overlapping player and allows immediate movement',()=>{for(const [key,[x,y]]of Object.entries(FORT_POS)){const g=game();g.state.bank={gold:10000,stone:10000,wood:10000,ember:100,food:0};g.enterFortress();g.p.x=x;g.p.y=y;assert.ok(g.build(key));assert.equal(g.isBlocked(g.p.x,g.p.y),false,key);const before={...g.p};g.move(0,1,.1,stats(g.state));assert.ok(g.p.x!==before.x||g.p.y!==before.y,key);}});
test('existing trapped saves can escape solid geometry',()=>{const g=game();g.enterFortress();const p=g.world.props.find(p=>p.solid);g.p.x=p.x;g.p.y=p.y;g.move(1,0,.016,stats(g.state));assert.equal(g.isBlocked(g.p.x,g.p.y),false);});
test('one interaction gathers a resource and duplicate taps cannot grant it again',()=>{const g=game(),n=g.world.nodes.find(n=>n.type==='wood');g.p.x=n.x;g.p.y=n.y;g.interact(n);assert.ok(g.state.bag.wood>=6);const amount=g.state.bag.wood;g.interact(n);assert.equal(g.state.bag.wood,amount);assert.equal(g.available(n),false);});
